apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

images:
  - name: ghcr.io/aburan28/parallax-operator
    newTag: latest
  - name: ghcr.io/aburan28/parallax-plugins
    newTag: latest
