apiVersion: v1
kind: ServiceAccount
metadata:
  name: parallax-controller-manager
  namespace: parallax-system
  labels:
    app.kubernetes.io/name: parallax
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
