// Capture plugins tap live traffic on the system under test, filter it at the
// datapath (first-party: in-kernel via eBPF at L7), and forward the matched
// records to a capture service — e.g. kapture's capture ingest, where they land
// as versioned datasets replayable by a loaddriver (DESIGN.md §5.1).
//
// The ABI is datapath- and protocol-agnostic: parallax knows only that a capture
// plugin validates a filter spec, starts a session, reports progress, can swap
// the live filter set, and stops with summary metrics. What a "filter" matches —
// HTTP methods, gRPC services, header predicates, kernel- vs userspace-stage
// evaluation — is entirely the plugin's business, published through its config
// schema (docs/GENERALIZATION.md G1). capture-ebpf owns the eBPF L7 vocabulary.
//
// Swap boundary: trial (a running session pins its plugin).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugin/v1/capture.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Capture_Plan_FullMethodName          = "/parallax.plugin.v1.Capture/Plan"
	Capture_Start_FullMethodName         = "/parallax.plugin.v1.Capture/Start"
	Capture_Status_FullMethodName        = "/parallax.plugin.v1.Capture/Status"
	Capture_UpdateFilters_FullMethodName = "/parallax.plugin.v1.Capture/UpdateFilters"
	Capture_Stop_FullMethodName          = "/parallax.plugin.v1.Capture/Stop"
)

// CaptureClient is the client API for Capture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaptureClient interface {
	// Plan validates and compiles the filter spec without attaching anything, and
	// reports what the session would do (programs, kernel-map entries, sink).
	Plan(ctx context.Context, in *CapturePlanRequest, opts ...grpc.CallOption) (*CapturePlanResponse, error)
	// Start attaches the datapath and begins forwarding matched records to the
	// capture sink. Returns an opaque handle for Status/UpdateFilters/Stop.
	Start(ctx context.Context, in *CaptureStartRequest, opts ...grpc.CallOption) (*CaptureStartResponse, error)
	// Status polls a running session. Unary rather than streaming so a reconcile
	// loop can consume it: one call per reconcile, no cross-reconcile stream state.
	Status(ctx context.Context, in *CaptureStatusRequest, opts ...grpc.CallOption) (*CaptureStatusResponse, error)
	// UpdateFilters replaces the live filter set in place — for eBPF this is a
	// map swap, no detach — so a session survives a mid-trial filter change.
	UpdateFilters(ctx context.Context, in *CaptureUpdateFiltersRequest, opts ...grpc.CallOption) (*CaptureUpdateFiltersResponse, error)
	// Stop detaches the datapath, flushes the sink, and returns summary metrics.
	Stop(ctx context.Context, in *CaptureStopRequest, opts ...grpc.CallOption) (*CaptureStopResponse, error)
}

type captureClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureClient(cc grpc.ClientConnInterface) CaptureClient {
	return &captureClient{cc}
}

func (c *captureClient) Plan(ctx context.Context, in *CapturePlanRequest, opts ...grpc.CallOption) (*CapturePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapturePlanResponse)
	err := c.cc.Invoke(ctx, Capture_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureClient) Start(ctx context.Context, in *CaptureStartRequest, opts ...grpc.CallOption) (*CaptureStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureStartResponse)
	err := c.cc.Invoke(ctx, Capture_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureClient) Status(ctx context.Context, in *CaptureStatusRequest, opts ...grpc.CallOption) (*CaptureStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureStatusResponse)
	err := c.cc.Invoke(ctx, Capture_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureClient) UpdateFilters(ctx context.Context, in *CaptureUpdateFiltersRequest, opts ...grpc.CallOption) (*CaptureUpdateFiltersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureUpdateFiltersResponse)
	err := c.cc.Invoke(ctx, Capture_UpdateFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureClient) Stop(ctx context.Context, in *CaptureStopRequest, opts ...grpc.CallOption) (*CaptureStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureStopResponse)
	err := c.cc.Invoke(ctx, Capture_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureServer is the server API for Capture service.
// All implementations must embed UnimplementedCaptureServer
// for forward compatibility.
type CaptureServer interface {
	// Plan validates and compiles the filter spec without attaching anything, and
	// reports what the session would do (programs, kernel-map entries, sink).
	Plan(context.Context, *CapturePlanRequest) (*CapturePlanResponse, error)
	// Start attaches the datapath and begins forwarding matched records to the
	// capture sink. Returns an opaque handle for Status/UpdateFilters/Stop.
	Start(context.Context, *CaptureStartRequest) (*CaptureStartResponse, error)
	// Status polls a running session. Unary rather than streaming so a reconcile
	// loop can consume it: one call per reconcile, no cross-reconcile stream state.
	Status(context.Context, *CaptureStatusRequest) (*CaptureStatusResponse, error)
	// UpdateFilters replaces the live filter set in place — for eBPF this is a
	// map swap, no detach — so a session survives a mid-trial filter change.
	UpdateFilters(context.Context, *CaptureUpdateFiltersRequest) (*CaptureUpdateFiltersResponse, error)
	// Stop detaches the datapath, flushes the sink, and returns summary metrics.
	Stop(context.Context, *CaptureStopRequest) (*CaptureStopResponse, error)
	mustEmbedUnimplementedCaptureServer()
}

// UnimplementedCaptureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureServer struct{}

func (UnimplementedCaptureServer) Plan(context.Context, *CapturePlanRequest) (*CapturePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedCaptureServer) Start(context.Context, *CaptureStartRequest) (*CaptureStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedCaptureServer) Status(context.Context, *CaptureStatusRequest) (*CaptureStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCaptureServer) UpdateFilters(context.Context, *CaptureUpdateFiltersRequest) (*CaptureUpdateFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFilters not implemented")
}
func (UnimplementedCaptureServer) Stop(context.Context, *CaptureStopRequest) (*CaptureStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCaptureServer) mustEmbedUnimplementedCaptureServer() {}
func (UnimplementedCaptureServer) testEmbeddedByValue()                 {}

// UnsafeCaptureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServer will
// result in compilation errors.
type UnsafeCaptureServer interface {
	mustEmbedUnimplementedCaptureServer()
}

func RegisterCaptureServer(s grpc.ServiceRegistrar, srv CaptureServer) {
	// If the following call pancis, it indicates UnimplementedCaptureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Capture_ServiceDesc, srv)
}

func _Capture_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapturePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capture_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).Plan(ctx, req.(*CapturePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capture_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capture_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).Start(ctx, req.(*CaptureStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capture_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capture_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).Status(ctx, req.(*CaptureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capture_UpdateFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureUpdateFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).UpdateFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capture_UpdateFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).UpdateFilters(ctx, req.(*CaptureUpdateFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capture_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capture_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).Stop(ctx, req.(*CaptureStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capture_ServiceDesc is the grpc.ServiceDesc for Capture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.plugin.v1.Capture",
	HandlerType: (*CaptureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _Capture_Plan_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Capture_Start_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Capture_Status_Handler,
		},
		{
			MethodName: "UpdateFilters",
			Handler:    _Capture_UpdateFilters_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Capture_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/capture.proto",
}
