// Capture plugins tap live traffic on the system under test, filter it at the
// datapath (first-party: in-kernel via eBPF at L7), and forward the matched
// records to a capture service — e.g. kapture's capture ingest, where they land
// as versioned datasets replayable by a loaddriver (DESIGN.md §5.1).
//
// The ABI is datapath- and protocol-agnostic: parallax knows only that a capture
// plugin validates a filter spec, starts a session, reports progress, can swap
// the live filter set, and stops with summary metrics. What a "filter" matches —
// HTTP methods, gRPC services, header predicates, kernel- vs userspace-stage
// evaluation — is entirely the plugin's business, published through its config
// schema (docs/GENERALIZATION.md G1). capture-ebpf owns the eBPF L7 vocabulary.
//
// Swap boundary: trial (a running session pins its plugin).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/capture.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapturePlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolved capture block: attach point, filter set, sink. Plugin-owned
	// vocabulary, schema-validated via Describe().
	CaptureJson   []byte `protobuf:"bytes,1,opt,name=capture_json,json=captureJson,proto3" json:"capture_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePlanRequest) Reset() {
	*x = CapturePlanRequest{}
	mi := &file_plugin_v1_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePlanRequest) ProtoMessage() {}

func (x *CapturePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePlanRequest.ProtoReflect.Descriptor instead.
func (*CapturePlanRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{0}
}

func (x *CapturePlanRequest) GetCaptureJson() []byte {
	if x != nil {
		return x.CaptureJson
	}
	return nil
}

type CapturePlanResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// Plugin-defined plan facts for the trial record (compiled program count,
	// kernel map entries, userspace-stage filter count, sampling percent, ...).
	// Purely informational to the core.
	Plan          map[string]float64 `protobuf:"bytes,3,rep,name=plan,proto3" json:"plan,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePlanResponse) Reset() {
	*x = CapturePlanResponse{}
	mi := &file_plugin_v1_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePlanResponse) ProtoMessage() {}

func (x *CapturePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePlanResponse.ProtoReflect.Descriptor instead.
func (*CapturePlanResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{1}
}

func (x *CapturePlanResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CapturePlanResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CapturePlanResponse) GetPlan() map[string]float64 {
	if x != nil {
		return x.Plan
	}
	return nil
}

type CaptureStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptureJson   []byte                 `protobuf:"bytes,1,opt,name=capture_json,json=captureJson,proto3" json:"capture_json,omitempty"`
	TrialId       string                 `protobuf:"bytes,2,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStartRequest) Reset() {
	*x = CaptureStartRequest{}
	mi := &file_plugin_v1_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStartRequest) ProtoMessage() {}

func (x *CaptureStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStartRequest.ProtoReflect.Descriptor instead.
func (*CaptureStartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureStartRequest) GetCaptureJson() []byte {
	if x != nil {
		return x.CaptureJson
	}
	return nil
}

func (x *CaptureStartRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type CaptureStartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle the plugin chooses (a link/attachment id, a session UUID). The
	// host persists it and hands it back on Status/UpdateFilters/Stop — plugins
	// are never required to key sessions by trial id.
	SessionRef    string `protobuf:"bytes,1,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStartResponse) Reset() {
	*x = CaptureStartResponse{}
	mi := &file_plugin_v1_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStartResponse) ProtoMessage() {}

func (x *CaptureStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStartResponse.ProtoReflect.Descriptor instead.
func (*CaptureStartResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureStartResponse) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

func (x *CaptureStartResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CaptureStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionRef    string                 `protobuf:"bytes,1,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStatusRequest) Reset() {
	*x = CaptureStatusRequest{}
	mi := &file_plugin_v1_capture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStatusRequest) ProtoMessage() {}

func (x *CaptureStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStatusRequest.ProtoReflect.Descriptor instead.
func (*CaptureStatusRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureStatusRequest) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

type CaptureStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin-defined phase label, surfaced in trial events.
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Plugin-defined progress counters: seen_records / matched_records /
	// forwarded_records / dropped_records for the eBPF plugin, and so on.
	Metrics map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Aborted reports that the session's own abort policy fired (sink unreachable,
	// datapath detached by the kernel, drop budget exceeded). The trial terminates
	// as Aborted and is recorded.
	Aborted       bool   `protobuf:"varint,3,opt,name=aborted,proto3" json:"aborted,omitempty"`
	AbortReason   string `protobuf:"bytes,4,opt,name=abort_reason,json=abortReason,proto3" json:"abort_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStatusResponse) Reset() {
	*x = CaptureStatusResponse{}
	mi := &file_plugin_v1_capture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStatusResponse) ProtoMessage() {}

func (x *CaptureStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStatusResponse.ProtoReflect.Descriptor instead.
func (*CaptureStatusResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{5}
}

func (x *CaptureStatusResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *CaptureStatusResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CaptureStatusResponse) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *CaptureStatusResponse) GetAbortReason() string {
	if x != nil {
		return x.AbortReason
	}
	return ""
}

type CaptureUpdateFiltersRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionRef string                 `protobuf:"bytes,1,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	// Replacement capture block; only the filter set may change mid-session.
	CaptureJson   []byte `protobuf:"bytes,2,opt,name=capture_json,json=captureJson,proto3" json:"capture_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureUpdateFiltersRequest) Reset() {
	*x = CaptureUpdateFiltersRequest{}
	mi := &file_plugin_v1_capture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureUpdateFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureUpdateFiltersRequest) ProtoMessage() {}

func (x *CaptureUpdateFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureUpdateFiltersRequest.ProtoReflect.Descriptor instead.
func (*CaptureUpdateFiltersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureUpdateFiltersRequest) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

func (x *CaptureUpdateFiltersRequest) GetCaptureJson() []byte {
	if x != nil {
		return x.CaptureJson
	}
	return nil
}

type CaptureUpdateFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureUpdateFiltersResponse) Reset() {
	*x = CaptureUpdateFiltersResponse{}
	mi := &file_plugin_v1_capture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureUpdateFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureUpdateFiltersResponse) ProtoMessage() {}

func (x *CaptureUpdateFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureUpdateFiltersResponse.ProtoReflect.Descriptor instead.
func (*CaptureUpdateFiltersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{7}
}

func (x *CaptureUpdateFiltersResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CaptureUpdateFiltersResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CaptureStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionRef    string                 `protobuf:"bytes,1,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStopRequest) Reset() {
	*x = CaptureStopRequest{}
	mi := &file_plugin_v1_capture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStopRequest) ProtoMessage() {}

func (x *CaptureStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStopRequest.ProtoReflect.Descriptor instead.
func (*CaptureStopRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{8}
}

func (x *CaptureStopRequest) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

type CaptureStopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Summary metrics for the whole session, keyed by plugin-defined metric name.
	// These names are the plugin's published contract: capture-ebpf publishes
	// seen_records / matched_records / forwarded_records / dropped_records /
	// forwarded_bytes / duration_ms.
	Metrics map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Full plugin-native session report, retained as a trial artifact and
	// available to exporters. Not interpreted by the core.
	ReportJson    []byte `protobuf:"bytes,3,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStopResponse) Reset() {
	*x = CaptureStopResponse{}
	mi := &file_plugin_v1_capture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStopResponse) ProtoMessage() {}

func (x *CaptureStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_capture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStopResponse.ProtoReflect.Descriptor instead.
func (*CaptureStopResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_capture_proto_rawDescGZIP(), []int{9}
}

func (x *CaptureStopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CaptureStopResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CaptureStopResponse) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

func (x *CaptureStopResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_plugin_v1_capture_proto protoreflect.FileDescriptor

const file_plugin_v1_capture_proto_rawDesc = "" +
	"\n" +
	"\x17plugin/v1/capture.proto\x12\x12parallax.plugin.v1\"7\n" +
	"\x12CapturePlanRequest\x12!\n" +
	"\fcapture_json\x18\x01 \x01(\fR\vcaptureJson\"\xbd\x01\n" +
	"\x13CapturePlanResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12E\n" +
	"\x04plan\x18\x03 \x03(\v21.parallax.plugin.v1.CapturePlanResponse.PlanEntryR\x04plan\x1a7\n" +
	"\tPlanEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"S\n" +
	"\x13CaptureStartRequest\x12!\n" +
	"\fcapture_json\x18\x01 \x01(\fR\vcaptureJson\x12\x19\n" +
	"\btrial_id\x18\x02 \x01(\tR\atrialId\"O\n" +
	"\x14CaptureStartResponse\x12\x1f\n" +
	"\vsession_ref\x18\x01 \x01(\tR\n" +
	"sessionRef\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"7\n" +
	"\x14CaptureStatusRequest\x12\x1f\n" +
	"\vsession_ref\x18\x01 \x01(\tR\n" +
	"sessionRef\"\xf8\x01\n" +
	"\x15CaptureStatusResponse\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12P\n" +
	"\ametrics\x18\x02 \x03(\v26.parallax.plugin.v1.CaptureStatusResponse.MetricsEntryR\ametrics\x12\x18\n" +
	"\aaborted\x18\x03 \x01(\bR\aaborted\x12!\n" +
	"\fabort_reason\x18\x04 \x01(\tR\vabortReason\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"a\n" +
	"\x1bCaptureUpdateFiltersRequest\x12\x1f\n" +
	"\vsession_ref\x18\x01 \x01(\tR\n" +
	"sessionRef\x12!\n" +
	"\fcapture_json\x18\x02 \x01(\fR\vcaptureJson\"F\n" +
	"\x1cCaptureUpdateFiltersResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"5\n" +
	"\x12CaptureStopRequest\x12\x1f\n" +
	"\vsession_ref\x18\x01 \x01(\tR\n" +
	"sessionRef\"\xea\x01\n" +
	"\x13CaptureStopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12N\n" +
	"\ametrics\x18\x02 \x03(\v24.parallax.plugin.v1.CaptureStopResponse.MetricsEntryR\ametrics\x12\x1f\n" +
	"\vreport_json\x18\x03 \x01(\fR\n" +
	"reportJson\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xea\x03\n" +
	"\aCapture\x12W\n" +
	"\x04Plan\x12&.parallax.plugin.v1.CapturePlanRequest\x1a'.parallax.plugin.v1.CapturePlanResponse\x12Z\n" +
	"\x05Start\x12'.parallax.plugin.v1.CaptureStartRequest\x1a(.parallax.plugin.v1.CaptureStartResponse\x12]\n" +
	"\x06Status\x12(.parallax.plugin.v1.CaptureStatusRequest\x1a).parallax.plugin.v1.CaptureStatusResponse\x12r\n" +
	"\rUpdateFilters\x12/.parallax.plugin.v1.CaptureUpdateFiltersRequest\x1a0.parallax.plugin.v1.CaptureUpdateFiltersResponse\x12W\n" +
	"\x04Stop\x12&.parallax.plugin.v1.CaptureStopRequest\x1a'.parallax.plugin.v1.CaptureStopResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_capture_proto_rawDescOnce sync.Once
	file_plugin_v1_capture_proto_rawDescData []byte
)

func file_plugin_v1_capture_proto_rawDescGZIP() []byte {
	file_plugin_v1_capture_proto_rawDescOnce.Do(func() {
		file_plugin_v1_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_capture_proto_rawDesc), len(file_plugin_v1_capture_proto_rawDesc)))
	})
	return file_plugin_v1_capture_proto_rawDescData
}

var file_plugin_v1_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_plugin_v1_capture_proto_goTypes = []any{
	(*CapturePlanRequest)(nil),           // 0: parallax.plugin.v1.CapturePlanRequest
	(*CapturePlanResponse)(nil),          // 1: parallax.plugin.v1.CapturePlanResponse
	(*CaptureStartRequest)(nil),          // 2: parallax.plugin.v1.CaptureStartRequest
	(*CaptureStartResponse)(nil),         // 3: parallax.plugin.v1.CaptureStartResponse
	(*CaptureStatusRequest)(nil),         // 4: parallax.plugin.v1.CaptureStatusRequest
	(*CaptureStatusResponse)(nil),        // 5: parallax.plugin.v1.CaptureStatusResponse
	(*CaptureUpdateFiltersRequest)(nil),  // 6: parallax.plugin.v1.CaptureUpdateFiltersRequest
	(*CaptureUpdateFiltersResponse)(nil), // 7: parallax.plugin.v1.CaptureUpdateFiltersResponse
	(*CaptureStopRequest)(nil),           // 8: parallax.plugin.v1.CaptureStopRequest
	(*CaptureStopResponse)(nil),          // 9: parallax.plugin.v1.CaptureStopResponse
	nil,                                  // 10: parallax.plugin.v1.CapturePlanResponse.PlanEntry
	nil,                                  // 11: parallax.plugin.v1.CaptureStatusResponse.MetricsEntry
	nil,                                  // 12: parallax.plugin.v1.CaptureStopResponse.MetricsEntry
}
var file_plugin_v1_capture_proto_depIdxs = []int32{
	10, // 0: parallax.plugin.v1.CapturePlanResponse.plan:type_name -> parallax.plugin.v1.CapturePlanResponse.PlanEntry
	11, // 1: parallax.plugin.v1.CaptureStatusResponse.metrics:type_name -> parallax.plugin.v1.CaptureStatusResponse.MetricsEntry
	12, // 2: parallax.plugin.v1.CaptureStopResponse.metrics:type_name -> parallax.plugin.v1.CaptureStopResponse.MetricsEntry
	0,  // 3: parallax.plugin.v1.Capture.Plan:input_type -> parallax.plugin.v1.CapturePlanRequest
	2,  // 4: parallax.plugin.v1.Capture.Start:input_type -> parallax.plugin.v1.CaptureStartRequest
	4,  // 5: parallax.plugin.v1.Capture.Status:input_type -> parallax.plugin.v1.CaptureStatusRequest
	6,  // 6: parallax.plugin.v1.Capture.UpdateFilters:input_type -> parallax.plugin.v1.CaptureUpdateFiltersRequest
	8,  // 7: parallax.plugin.v1.Capture.Stop:input_type -> parallax.plugin.v1.CaptureStopRequest
	1,  // 8: parallax.plugin.v1.Capture.Plan:output_type -> parallax.plugin.v1.CapturePlanResponse
	3,  // 9: parallax.plugin.v1.Capture.Start:output_type -> parallax.plugin.v1.CaptureStartResponse
	5,  // 10: parallax.plugin.v1.Capture.Status:output_type -> parallax.plugin.v1.CaptureStatusResponse
	7,  // 11: parallax.plugin.v1.Capture.UpdateFilters:output_type -> parallax.plugin.v1.CaptureUpdateFiltersResponse
	9,  // 12: parallax.plugin.v1.Capture.Stop:output_type -> parallax.plugin.v1.CaptureStopResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_v1_capture_proto_init() }
func file_plugin_v1_capture_proto_init() {
	if File_plugin_v1_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_capture_proto_rawDesc), len(file_plugin_v1_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_capture_proto_goTypes,
		DependencyIndexes: file_plugin_v1_capture_proto_depIdxs,
		MessageInfos:      file_plugin_v1_capture_proto_msgTypes,
	}.Build()
	File_plugin_v1_capture_proto = out.File
	file_plugin_v1_capture_proto_goTypes = nil
	file_plugin_v1_capture_proto_depIdxs = nil
}
