// Exporter plugins fan study lifecycle events out to external systems
// (webhook, Slack, OCI bundle) — DESIGN.md §5.1. Swap boundary: anytime (idempotent).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/exporter.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// runreport | prom-snapshot | readback | k8s-dump | report
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Uri           string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Digest        string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_plugin_v1_exporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_exporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_plugin_v1_exporter_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArtifactRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event name, e.g. study.started, trial.collected, candidate.promoted.
	Event         string         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	PayloadJson   []byte         `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Refs          []*ArtifactRef `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_plugin_v1_exporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_exporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_exporter_proto_rawDescGZIP(), []int{1}
}

func (x *ExportRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ExportRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *ExportRequest) GetRefs() []*ArtifactRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_plugin_v1_exporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_exporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_exporter_proto_rawDescGZIP(), []int{2}
}

func (x *ExportResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExportResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_plugin_v1_exporter_proto protoreflect.FileDescriptor

const file_plugin_v1_exporter_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/v1/exporter.proto\x12\x12parallax.plugin.v1\"K\n" +
	"\vArtifactRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"}\n" +
	"\rExportRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x123\n" +
	"\x04refs\x18\x03 \x03(\v2\x1f.parallax.plugin.v1.ArtifactRefR\x04refs\"8\n" +
	"\x0eExportResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail2[\n" +
	"\bExporter\x12O\n" +
	"\x06Export\x12!.parallax.plugin.v1.ExportRequest\x1a\".parallax.plugin.v1.ExportResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_exporter_proto_rawDescOnce sync.Once
	file_plugin_v1_exporter_proto_rawDescData []byte
)

func file_plugin_v1_exporter_proto_rawDescGZIP() []byte {
	file_plugin_v1_exporter_proto_rawDescOnce.Do(func() {
		file_plugin_v1_exporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_exporter_proto_rawDesc), len(file_plugin_v1_exporter_proto_rawDesc)))
	})
	return file_plugin_v1_exporter_proto_rawDescData
}

var file_plugin_v1_exporter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_v1_exporter_proto_goTypes = []any{
	(*ArtifactRef)(nil),    // 0: parallax.plugin.v1.ArtifactRef
	(*ExportRequest)(nil),  // 1: parallax.plugin.v1.ExportRequest
	(*ExportResponse)(nil), // 2: parallax.plugin.v1.ExportResponse
}
var file_plugin_v1_exporter_proto_depIdxs = []int32{
	0, // 0: parallax.plugin.v1.ExportRequest.refs:type_name -> parallax.plugin.v1.ArtifactRef
	1, // 1: parallax.plugin.v1.Exporter.Export:input_type -> parallax.plugin.v1.ExportRequest
	2, // 2: parallax.plugin.v1.Exporter.Export:output_type -> parallax.plugin.v1.ExportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_v1_exporter_proto_init() }
func file_plugin_v1_exporter_proto_init() {
	if File_plugin_v1_exporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_exporter_proto_rawDesc), len(file_plugin_v1_exporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_exporter_proto_goTypes,
		DependencyIndexes: file_plugin_v1_exporter_proto_depIdxs,
		MessageInfos:      file_plugin_v1_exporter_proto_msgTypes,
	}.Build()
	File_plugin_v1_exporter_proto = out.File
	file_plugin_v1_exporter_proto_goTypes = nil
	file_plugin_v1_exporter_proto_depIdxs = nil
}
