// The parallax plugin ABI (DESIGN.md §5.2). Every plugin — regardless of kind —
// serves the Lifecycle service plus exactly one kind service (target, loaddriver,
// provider, strategy, scenario, exporter, capture) on the same gRPC server over a
// unix socket.
//
// Process contract (§5.2): the host launches the binary with the magic-cookie env
// PARALLAX_PLUGIN_MAGIC=parallax-plugin and a socket-dir env; the plugin prints
// exactly one stdout line `PARALLAX-PLUGIN|1|unix|<socket-path>|grpc` within 15s and
// logs only to stderr. Discovery is by naming convention `parallax-<kind>-<name>`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugin/v1/lifecycle.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lifecycle_Describe_FullMethodName  = "/parallax.plugin.v1.Lifecycle/Describe"
	Lifecycle_Configure_FullMethodName = "/parallax.plugin.v1.Lifecycle/Configure"
	Lifecycle_Health_FullMethodName    = "/parallax.plugin.v1.Lifecycle/Health"
	Lifecycle_Drain_FullMethodName     = "/parallax.plugin.v1.Lifecycle/Drain"
)

// LifecycleClient is the client API for Lifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Lifecycle is implemented by every plugin. The host uses Describe for ABI version
// negotiation, Configure for fail-fast config validation, Health for its supervisor
// loop, and Drain for hot-reload / shutdown (idempotent).
type LifecycleClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type lifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewLifecycleClient(cc grpc.ClientConnInterface) LifecycleClient {
	return &lifecycleClient{cc}
}

func (c *lifecycleClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, Lifecycle_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, Lifecycle_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Lifecycle_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, Lifecycle_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifecycleServer is the server API for Lifecycle service.
// All implementations must embed UnimplementedLifecycleServer
// for forward compatibility.
//
// Lifecycle is implemented by every plugin. The host uses Describe for ABI version
// negotiation, Configure for fail-fast config validation, Health for its supervisor
// loop, and Drain for hot-reload / shutdown (idempotent).
type LifecycleServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	mustEmbedUnimplementedLifecycleServer()
}

// UnimplementedLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifecycleServer struct{}

func (UnimplementedLifecycleServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedLifecycleServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedLifecycleServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLifecycleServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedLifecycleServer) mustEmbedUnimplementedLifecycleServer() {}
func (UnimplementedLifecycleServer) testEmbeddedByValue()                   {}

// UnsafeLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifecycleServer will
// result in compilation errors.
type UnsafeLifecycleServer interface {
	mustEmbedUnimplementedLifecycleServer()
}

func RegisterLifecycleServer(s grpc.ServiceRegistrar, srv LifecycleServer) {
	// If the following call pancis, it indicates UnimplementedLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lifecycle_ServiceDesc, srv)
}

func _Lifecycle_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lifecycle_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lifecycle_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lifecycle_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lifecycle_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lifecycle_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lifecycle_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lifecycle_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lifecycle_ServiceDesc is the grpc.ServiceDesc for Lifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.plugin.v1.Lifecycle",
	HandlerType: (*LifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Lifecycle_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Lifecycle_Configure_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Lifecycle_Health_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _Lifecycle_Drain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/lifecycle.proto",
}
