// The parallax plugin ABI (DESIGN.md §5.2). Every plugin — regardless of kind —
// serves the Lifecycle service plus exactly one kind service (target, loaddriver,
// provider, strategy, scenario, exporter, capture) on the same gRPC server over a
// unix socket.
//
// Process contract (§5.2): the host launches the binary with the magic-cookie env
// PARALLAX_PLUGIN_MAGIC=parallax-plugin and a socket-dir env; the plugin prints
// exactly one stdout line `PARALLAX-PLUGIN|1|unix|<socket-path>|grpc` within 15s and
// logs only to stderr. Discovery is by naming convention `parallax-<kind>-<name>`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/lifecycle.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginKind enumerates the seven extension seams (DESIGN.md §5.1).
type PluginKind int32

const (
	PluginKind_PLUGIN_KIND_UNSPECIFIED PluginKind = 0
	PluginKind_PLUGIN_KIND_TARGET      PluginKind = 1
	PluginKind_PLUGIN_KIND_LOADDRIVER  PluginKind = 2
	PluginKind_PLUGIN_KIND_PROVIDER    PluginKind = 3
	PluginKind_PLUGIN_KIND_STRATEGY    PluginKind = 4
	PluginKind_PLUGIN_KIND_SCENARIO    PluginKind = 5
	PluginKind_PLUGIN_KIND_EXPORTER    PluginKind = 6
	PluginKind_PLUGIN_KIND_CAPTURE     PluginKind = 7
)

// Enum value maps for PluginKind.
var (
	PluginKind_name = map[int32]string{
		0: "PLUGIN_KIND_UNSPECIFIED",
		1: "PLUGIN_KIND_TARGET",
		2: "PLUGIN_KIND_LOADDRIVER",
		3: "PLUGIN_KIND_PROVIDER",
		4: "PLUGIN_KIND_STRATEGY",
		5: "PLUGIN_KIND_SCENARIO",
		6: "PLUGIN_KIND_EXPORTER",
		7: "PLUGIN_KIND_CAPTURE",
	}
	PluginKind_value = map[string]int32{
		"PLUGIN_KIND_UNSPECIFIED": 0,
		"PLUGIN_KIND_TARGET":      1,
		"PLUGIN_KIND_LOADDRIVER":  2,
		"PLUGIN_KIND_PROVIDER":    3,
		"PLUGIN_KIND_STRATEGY":    4,
		"PLUGIN_KIND_SCENARIO":    5,
		"PLUGIN_KIND_EXPORTER":    6,
		"PLUGIN_KIND_CAPTURE":     7,
	}
)

func (x PluginKind) Enum() *PluginKind {
	p := new(PluginKind)
	*p = x
	return p
}

func (x PluginKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginKind) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_lifecycle_proto_enumTypes[0].Descriptor()
}

func (PluginKind) Type() protoreflect.EnumType {
	return &file_plugin_v1_lifecycle_proto_enumTypes[0]
}

func (x PluginKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginKind.Descriptor instead.
func (PluginKind) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

// BuildInfo is stamped at build time and recorded in the plugin_audit trail.
type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	VcsRef        string                 `protobuf:"bytes,2,opt,name=vcs_ref,json=vcsRef,proto3" json:"vcs_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *BuildInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildInfo) GetVcsRef() string {
	if x != nil {
		return x.VcsRef
	}
	return ""
}

type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ABI versions the host supports; the plugin picks one it also supports (N-1).
	HostAbiVersions []string `protobuf:"bytes,1,rep,name=host_abi_versions,json=hostAbiVersions,proto3" json:"host_abi_versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeRequest) GetHostAbiVersions() []string {
	if x != nil {
		return x.HostAbiVersions
	}
	return nil
}

type DescribeResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind        PluginKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=parallax.plugin.v1.PluginKind" json:"kind,omitempty"`
	AbiVersions []string               `protobuf:"bytes,3,rep,name=abi_versions,json=abiVersions,proto3" json:"abi_versions,omitempty"`
	// The version the plugin selected from host_abi_versions; empty ⇒ no overlap.
	SelectedAbiVersion string `protobuf:"bytes,4,opt,name=selected_abi_version,json=selectedAbiVersion,proto3" json:"selected_abi_version,omitempty"`
	// JSON Schema (draft 2020-12) for this plugin's config block.
	ConfigSchema  string     `protobuf:"bytes,5,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Capabilities  []string   `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Build         *BuildInfo `protobuf:"bytes,7,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetKind() PluginKind {
	if x != nil {
		return x.Kind
	}
	return PluginKind_PLUGIN_KIND_UNSPECIFIED
}

func (x *DescribeResponse) GetAbiVersions() []string {
	if x != nil {
		return x.AbiVersions
	}
	return nil
}

func (x *DescribeResponse) GetSelectedAbiVersion() string {
	if x != nil {
		return x.SelectedAbiVersion
	}
	return ""
}

func (x *DescribeResponse) GetConfigSchema() string {
	if x != nil {
		return x.ConfigSchema
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetBuild() *BuildInfo {
	if x != nil {
		return x.Build
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CR-supplied config block, serialized as JSON.
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	AbiVersion    string `protobuf:"bytes,2,opt,name=abi_version,json=abiVersion,proto3" json:"abi_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ConfigureRequest) GetAbiVersion() string {
	if x != nil {
		return x.AbiVersion
	}
	return ""
}

type ConfigureResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// On rejection, a human-readable reason recorded verbatim in Plugin.status.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConfigureResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceSeconds  int64                  `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *DrainRequest) GetGraceSeconds() int64 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_lifecycle_proto_rawDescGZIP(), []int{8}
}

var File_plugin_v1_lifecycle_proto protoreflect.FileDescriptor

const file_plugin_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/v1/lifecycle.proto\x12\x12parallax.plugin.v1\">\n" +
	"\tBuildInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\avcs_ref\x18\x02 \x01(\tR\x06vcsRef\"=\n" +
	"\x0fDescribeRequest\x12*\n" +
	"\x11host_abi_versions\x18\x01 \x03(\tR\x0fhostAbiVersions\"\xad\x02\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.parallax.plugin.v1.PluginKindR\x04kind\x12!\n" +
	"\fabi_versions\x18\x03 \x03(\tR\vabiVersions\x120\n" +
	"\x14selected_abi_version\x18\x04 \x01(\tR\x12selectedAbiVersion\x12#\n" +
	"\rconfig_schema\x18\x05 \x01(\tR\fconfigSchema\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x123\n" +
	"\x05build\x18\a \x01(\v2\x1d.parallax.plugin.v1.BuildInfoR\x05build\"T\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1f\n" +
	"\vabi_version\x18\x02 \x01(\tR\n" +
	"abiVersion\"G\n" +
	"\x11ConfigureResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0f\n" +
	"\rHealthRequest\"8\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"3\n" +
	"\fDrainRequest\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\x03R\fgraceSeconds\"\x0f\n" +
	"\rDrainResponse*\xde\x01\n" +
	"\n" +
	"PluginKind\x12\x1b\n" +
	"\x17PLUGIN_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLUGIN_KIND_TARGET\x10\x01\x12\x1a\n" +
	"\x16PLUGIN_KIND_LOADDRIVER\x10\x02\x12\x18\n" +
	"\x14PLUGIN_KIND_PROVIDER\x10\x03\x12\x18\n" +
	"\x14PLUGIN_KIND_STRATEGY\x10\x04\x12\x18\n" +
	"\x14PLUGIN_KIND_SCENARIO\x10\x05\x12\x18\n" +
	"\x14PLUGIN_KIND_EXPORTER\x10\x06\x12\x17\n" +
	"\x13PLUGIN_KIND_CAPTURE\x10\a2\xdb\x02\n" +
	"\tLifecycle\x12U\n" +
	"\bDescribe\x12#.parallax.plugin.v1.DescribeRequest\x1a$.parallax.plugin.v1.DescribeResponse\x12X\n" +
	"\tConfigure\x12$.parallax.plugin.v1.ConfigureRequest\x1a%.parallax.plugin.v1.ConfigureResponse\x12O\n" +
	"\x06Health\x12!.parallax.plugin.v1.HealthRequest\x1a\".parallax.plugin.v1.HealthResponse\x12L\n" +
	"\x05Drain\x12 .parallax.plugin.v1.DrainRequest\x1a!.parallax.plugin.v1.DrainResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_lifecycle_proto_rawDescOnce sync.Once
	file_plugin_v1_lifecycle_proto_rawDescData []byte
)

func file_plugin_v1_lifecycle_proto_rawDescGZIP() []byte {
	file_plugin_v1_lifecycle_proto_rawDescOnce.Do(func() {
		file_plugin_v1_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_lifecycle_proto_rawDesc), len(file_plugin_v1_lifecycle_proto_rawDesc)))
	})
	return file_plugin_v1_lifecycle_proto_rawDescData
}

var file_plugin_v1_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_v1_lifecycle_proto_goTypes = []any{
	(PluginKind)(0),           // 0: parallax.plugin.v1.PluginKind
	(*BuildInfo)(nil),         // 1: parallax.plugin.v1.BuildInfo
	(*DescribeRequest)(nil),   // 2: parallax.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),  // 3: parallax.plugin.v1.DescribeResponse
	(*ConfigureRequest)(nil),  // 4: parallax.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 5: parallax.plugin.v1.ConfigureResponse
	(*HealthRequest)(nil),     // 6: parallax.plugin.v1.HealthRequest
	(*HealthResponse)(nil),    // 7: parallax.plugin.v1.HealthResponse
	(*DrainRequest)(nil),      // 8: parallax.plugin.v1.DrainRequest
	(*DrainResponse)(nil),     // 9: parallax.plugin.v1.DrainResponse
}
var file_plugin_v1_lifecycle_proto_depIdxs = []int32{
	0, // 0: parallax.plugin.v1.DescribeResponse.kind:type_name -> parallax.plugin.v1.PluginKind
	1, // 1: parallax.plugin.v1.DescribeResponse.build:type_name -> parallax.plugin.v1.BuildInfo
	2, // 2: parallax.plugin.v1.Lifecycle.Describe:input_type -> parallax.plugin.v1.DescribeRequest
	4, // 3: parallax.plugin.v1.Lifecycle.Configure:input_type -> parallax.plugin.v1.ConfigureRequest
	6, // 4: parallax.plugin.v1.Lifecycle.Health:input_type -> parallax.plugin.v1.HealthRequest
	8, // 5: parallax.plugin.v1.Lifecycle.Drain:input_type -> parallax.plugin.v1.DrainRequest
	3, // 6: parallax.plugin.v1.Lifecycle.Describe:output_type -> parallax.plugin.v1.DescribeResponse
	5, // 7: parallax.plugin.v1.Lifecycle.Configure:output_type -> parallax.plugin.v1.ConfigureResponse
	7, // 8: parallax.plugin.v1.Lifecycle.Health:output_type -> parallax.plugin.v1.HealthResponse
	9, // 9: parallax.plugin.v1.Lifecycle.Drain:output_type -> parallax.plugin.v1.DrainResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_lifecycle_proto_init() }
func file_plugin_v1_lifecycle_proto_init() {
	if File_plugin_v1_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_lifecycle_proto_rawDesc), len(file_plugin_v1_lifecycle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_plugin_v1_lifecycle_proto_depIdxs,
		EnumInfos:         file_plugin_v1_lifecycle_proto_enumTypes,
		MessageInfos:      file_plugin_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_plugin_v1_lifecycle_proto = out.File
	file_plugin_v1_lifecycle_proto_goTypes = nil
	file_plugin_v1_lifecycle_proto_depIdxs = nil
}
