// LoadDriver plugins generate load against the target (DESIGN.md §5.1).
//
// The ABI is workload-agnostic: parallax knows only that a driver starts something,
// reports progress, and stops with a set of metrics. What "load" means is entirely
// the driver's business — replayed HTTP traffic (loaddriver-kapture composes a
// CaptureLoadTest), a synthetic request generator, a submitted batch job, a query
// harness, an eval suite. Nothing request/response-shaped appears below
// (docs/GENERALIZATION.md G1, G5).
//
// Swap boundary: trial.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/loaddriver.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolved workload block: driver config, dataset reference, window durations.
	WorkloadJson  []byte `protobuf:"bytes,1,opt,name=workload_json,json=workloadJson,proto3" json:"workload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{0}
}

func (x *PlanRequest) GetWorkloadJson() []byte {
	if x != nil {
		return x.WorkloadJson
	}
	return nil
}

type PlanResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// Driver-defined plan facts for the trial record (shard count, job parallelism,
	// estimated duration, ...). Purely informational to the core.
	Plan          map[string]float64 `protobuf:"bytes,3,rep,name=plan,proto3" json:"plan,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{1}
}

func (x *PlanResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PlanResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PlanResponse) GetPlan() map[string]float64 {
	if x != nil {
		return x.Plan
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadJson  []byte                 `protobuf:"bytes,1,opt,name=workload_json,json=workloadJson,proto3" json:"workload_json,omitempty"`
	TrialId       string                 `protobuf:"bytes,2,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetWorkloadJson() []byte {
	if x != nil {
		return x.WorkloadJson
	}
	return nil
}

func (x *StartRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle the driver chooses (a CaptureLoadTest namespace/name, a Job UID, a
	// local run id). The host persists it and hands it back on Progress/Stop — drivers
	// are never required to key runs by trial id.
	RunRef        string `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

func (x *StartResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunRef        string                 `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressRequest) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

type ProgressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver-defined phase label, surfaced in trial events.
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Driver-defined progress counters: sent_requests / failed_requests for a request
	// driver, records_processed / splits_remaining for a batch driver, and so on.
	Metrics map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Done reports that the workload has run to completion. For workloads declaring
	// completion=driver this closes the measurement window.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// Aborted reports that the driver's own abort policy fired (error rate, duration
	// cap, target-safety trip). The trial terminates as Aborted and is recorded.
	Aborted       bool   `protobuf:"varint,4,opt,name=aborted,proto3" json:"aborted,omitempty"`
	AbortReason   string `protobuf:"bytes,5,opt,name=abort_reason,json=abortReason,proto3" json:"abort_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProgressResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ProgressResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ProgressResponse) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *ProgressResponse) GetAbortReason() string {
	if x != nil {
		return x.AbortReason
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunRef        string                 `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Summary metrics for the whole run, keyed by driver-defined metric name. This is
	// the surface a study's `slis[].driver` entries read, so these names are the
	// driver's published contract: a request driver publishes sent_requests /
	// p99_latency_ms, a batch driver publishes records_processed / job_duration_ms.
	Metrics map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Full driver-native report, retained as a trial artifact and available to
	// exporters. Not interpreted by the core.
	ReportJson    []byte `protobuf:"bytes,3,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StopResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *StopResponse) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

func (x *StopResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_plugin_v1_loaddriver_proto protoreflect.FileDescriptor

const file_plugin_v1_loaddriver_proto_rawDesc = "" +
	"\n" +
	"\x1aplugin/v1/loaddriver.proto\x12\x12parallax.plugin.v1\"2\n" +
	"\vPlanRequest\x12#\n" +
	"\rworkload_json\x18\x01 \x01(\fR\fworkloadJson\"\xaf\x01\n" +
	"\fPlanResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12>\n" +
	"\x04plan\x18\x03 \x03(\v2*.parallax.plugin.v1.PlanResponse.PlanEntryR\x04plan\x1a7\n" +
	"\tPlanEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"N\n" +
	"\fStartRequest\x12#\n" +
	"\rworkload_json\x18\x01 \x01(\fR\fworkloadJson\x12\x19\n" +
	"\btrial_id\x18\x02 \x01(\tR\atrialId\"@\n" +
	"\rStartResponse\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"*\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\"\x82\x02\n" +
	"\x10ProgressResponse\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12K\n" +
	"\ametrics\x18\x02 \x03(\v21.parallax.plugin.v1.ProgressResponse.MetricsEntryR\ametrics\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x18\n" +
	"\aaborted\x18\x04 \x01(\bR\aaborted\x12!\n" +
	"\fabort_reason\x18\x05 \x01(\tR\vabortReason\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\"\xdc\x01\n" +
	"\fStopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12G\n" +
	"\ametrics\x18\x02 \x03(\v2-.parallax.plugin.v1.StopResponse.MetricsEntryR\ametrics\x12\x1f\n" +
	"\vreport_json\x18\x03 \x01(\fR\n" +
	"reportJson\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xc7\x02\n" +
	"\n" +
	"LoadDriver\x12I\n" +
	"\x04Plan\x12\x1f.parallax.plugin.v1.PlanRequest\x1a .parallax.plugin.v1.PlanResponse\x12L\n" +
	"\x05Start\x12 .parallax.plugin.v1.StartRequest\x1a!.parallax.plugin.v1.StartResponse\x12U\n" +
	"\bProgress\x12#.parallax.plugin.v1.ProgressRequest\x1a$.parallax.plugin.v1.ProgressResponse\x12I\n" +
	"\x04Stop\x12\x1f.parallax.plugin.v1.StopRequest\x1a .parallax.plugin.v1.StopResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_loaddriver_proto_rawDescOnce sync.Once
	file_plugin_v1_loaddriver_proto_rawDescData []byte
)

func file_plugin_v1_loaddriver_proto_rawDescGZIP() []byte {
	file_plugin_v1_loaddriver_proto_rawDescOnce.Do(func() {
		file_plugin_v1_loaddriver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_loaddriver_proto_rawDesc), len(file_plugin_v1_loaddriver_proto_rawDesc)))
	})
	return file_plugin_v1_loaddriver_proto_rawDescData
}

var file_plugin_v1_loaddriver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plugin_v1_loaddriver_proto_goTypes = []any{
	(*PlanRequest)(nil),      // 0: parallax.plugin.v1.PlanRequest
	(*PlanResponse)(nil),     // 1: parallax.plugin.v1.PlanResponse
	(*StartRequest)(nil),     // 2: parallax.plugin.v1.StartRequest
	(*StartResponse)(nil),    // 3: parallax.plugin.v1.StartResponse
	(*ProgressRequest)(nil),  // 4: parallax.plugin.v1.ProgressRequest
	(*ProgressResponse)(nil), // 5: parallax.plugin.v1.ProgressResponse
	(*StopRequest)(nil),      // 6: parallax.plugin.v1.StopRequest
	(*StopResponse)(nil),     // 7: parallax.plugin.v1.StopResponse
	nil,                      // 8: parallax.plugin.v1.PlanResponse.PlanEntry
	nil,                      // 9: parallax.plugin.v1.ProgressResponse.MetricsEntry
	nil,                      // 10: parallax.plugin.v1.StopResponse.MetricsEntry
}
var file_plugin_v1_loaddriver_proto_depIdxs = []int32{
	8,  // 0: parallax.plugin.v1.PlanResponse.plan:type_name -> parallax.plugin.v1.PlanResponse.PlanEntry
	9,  // 1: parallax.plugin.v1.ProgressResponse.metrics:type_name -> parallax.plugin.v1.ProgressResponse.MetricsEntry
	10, // 2: parallax.plugin.v1.StopResponse.metrics:type_name -> parallax.plugin.v1.StopResponse.MetricsEntry
	0,  // 3: parallax.plugin.v1.LoadDriver.Plan:input_type -> parallax.plugin.v1.PlanRequest
	2,  // 4: parallax.plugin.v1.LoadDriver.Start:input_type -> parallax.plugin.v1.StartRequest
	4,  // 5: parallax.plugin.v1.LoadDriver.Progress:input_type -> parallax.plugin.v1.ProgressRequest
	6,  // 6: parallax.plugin.v1.LoadDriver.Stop:input_type -> parallax.plugin.v1.StopRequest
	1,  // 7: parallax.plugin.v1.LoadDriver.Plan:output_type -> parallax.plugin.v1.PlanResponse
	3,  // 8: parallax.plugin.v1.LoadDriver.Start:output_type -> parallax.plugin.v1.StartResponse
	5,  // 9: parallax.plugin.v1.LoadDriver.Progress:output_type -> parallax.plugin.v1.ProgressResponse
	7,  // 10: parallax.plugin.v1.LoadDriver.Stop:output_type -> parallax.plugin.v1.StopResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_v1_loaddriver_proto_init() }
func file_plugin_v1_loaddriver_proto_init() {
	if File_plugin_v1_loaddriver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_loaddriver_proto_rawDesc), len(file_plugin_v1_loaddriver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_loaddriver_proto_goTypes,
		DependencyIndexes: file_plugin_v1_loaddriver_proto_depIdxs,
		MessageInfos:      file_plugin_v1_loaddriver_proto_msgTypes,
	}.Build()
	File_plugin_v1_loaddriver_proto = out.File
	file_plugin_v1_loaddriver_proto_goTypes = nil
	file_plugin_v1_loaddriver_proto_depIdxs = nil
}
