// LoadDriver plugins generate load against the target (DESIGN.md §5.1).
//
// The ABI is workload-agnostic: parallax knows only that a driver starts something,
// reports progress, and stops with a set of metrics. What "load" means is entirely
// the driver's business — replayed HTTP traffic (loaddriver-kapture composes a
// CaptureLoadTest), a synthetic request generator, a submitted batch job, a query
// harness, an eval suite. Nothing request/response-shaped appears below
// (docs/GENERALIZATION.md G1, G5).
//
// Swap boundary: trial.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugin/v1/loaddriver.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadDriver_Plan_FullMethodName     = "/parallax.plugin.v1.LoadDriver/Plan"
	LoadDriver_Start_FullMethodName    = "/parallax.plugin.v1.LoadDriver/Start"
	LoadDriver_Progress_FullMethodName = "/parallax.plugin.v1.LoadDriver/Progress"
	LoadDriver_Stop_FullMethodName     = "/parallax.plugin.v1.LoadDriver/Stop"
)

// LoadDriverClient is the client API for LoadDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoadDriverClient interface {
	// Plan validates a workload before any trial is spent and reports what it would do.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// Start begins the run and returns an opaque handle for Progress/Stop.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Progress polls a running workload. Unary rather than streaming so a reconcile
	// loop can consume it: one call per reconcile, no cross-reconcile stream state.
	Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	// Stop ends the run and returns its summary metrics.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type loadDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadDriverClient(cc grpc.ClientConnInterface) LoadDriverClient {
	return &loadDriverClient{cc}
}

func (c *loadDriverClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, LoadDriver_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadDriverClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, LoadDriver_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadDriverClient) Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, LoadDriver_Progress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadDriverClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, LoadDriver_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadDriverServer is the server API for LoadDriver service.
// All implementations must embed UnimplementedLoadDriverServer
// for forward compatibility.
type LoadDriverServer interface {
	// Plan validates a workload before any trial is spent and reports what it would do.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// Start begins the run and returns an opaque handle for Progress/Stop.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Progress polls a running workload. Unary rather than streaming so a reconcile
	// loop can consume it: one call per reconcile, no cross-reconcile stream state.
	Progress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	// Stop ends the run and returns its summary metrics.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedLoadDriverServer()
}

// UnimplementedLoadDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadDriverServer struct{}

func (UnimplementedLoadDriverServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedLoadDriverServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedLoadDriverServer) Progress(context.Context, *ProgressRequest) (*ProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Progress not implemented")
}
func (UnimplementedLoadDriverServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedLoadDriverServer) mustEmbedUnimplementedLoadDriverServer() {}
func (UnimplementedLoadDriverServer) testEmbeddedByValue()                    {}

// UnsafeLoadDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadDriverServer will
// result in compilation errors.
type UnsafeLoadDriverServer interface {
	mustEmbedUnimplementedLoadDriverServer()
}

func RegisterLoadDriverServer(s grpc.ServiceRegistrar, srv LoadDriverServer) {
	// If the following call pancis, it indicates UnimplementedLoadDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadDriver_ServiceDesc, srv)
}

func _LoadDriver_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadDriverServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadDriver_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadDriverServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadDriver_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadDriverServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadDriver_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadDriverServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadDriver_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadDriverServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadDriver_Progress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadDriverServer).Progress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadDriver_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadDriverServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadDriver_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadDriverServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadDriver_ServiceDesc is the grpc.ServiceDesc for LoadDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.plugin.v1.LoadDriver",
	HandlerType: (*LoadDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _LoadDriver_Plan_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _LoadDriver_Start_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _LoadDriver_Progress_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _LoadDriver_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/loaddriver.proto",
}
