// LoadDriver plugins generate load against the target (DESIGN.md §5.1).
// loaddriver-kapture composes a CaptureLoadTest and watches its rollups.
// Swap boundary: trial.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/loaddriver.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadJson  []byte                 `protobuf:"bytes,1,opt,name=workload_json,json=workloadJson,proto3" json:"workload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{0}
}

func (x *PlanRequest) GetWorkloadJson() []byte {
	if x != nil {
		return x.WorkloadJson
	}
	return nil
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	TotalShards   int64                  `protobuf:"varint,3,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{1}
}

func (x *PlanResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PlanResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PlanResponse) GetTotalShards() int64 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadJson  []byte                 `protobuf:"bytes,1,opt,name=workload_json,json=workloadJson,proto3" json:"workload_json,omitempty"`
	TrialId       string                 `protobuf:"bytes,2,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetWorkloadJson() []byte {
	if x != nil {
		return x.WorkloadJson
	}
	return nil
}

func (x *StartRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle for Watch/Stop (e.g. the CaptureLoadTest namespace/name).
	RunRef        string `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

func (x *StartResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunRef        string                 `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

type WatchEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Phase          string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	SentRequests   int64                  `protobuf:"varint,2,opt,name=sent_requests,json=sentRequests,proto3" json:"sent_requests,omitempty"`
	FailedRequests int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AchievedRps    float64                `protobuf:"fixed64,4,opt,name=achieved_rps,json=achievedRps,proto3" json:"achieved_rps,omitempty"`
	Aborted        bool                   `protobuf:"varint,5,opt,name=aborted,proto3" json:"aborted,omitempty"`
	AbortReason    string                 `protobuf:"bytes,6,opt,name=abort_reason,json=abortReason,proto3" json:"abort_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{5}
}

func (x *WatchEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WatchEvent) GetSentRequests() int64 {
	if x != nil {
		return x.SentRequests
	}
	return 0
}

func (x *WatchEvent) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *WatchEvent) GetAchievedRps() float64 {
	if x != nil {
		return x.AchievedRps
	}
	return 0
}

func (x *WatchEvent) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *WatchEvent) GetAbortReason() string {
	if x != nil {
		return x.AbortReason
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunRef        string                 `protobuf:"bytes,1,opt,name=run_ref,json=runRef,proto3" json:"run_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetRunRef() string {
	if x != nil {
		return x.RunRef
	}
	return ""
}

// RunReport mirrors kapture's TrafficReplay run-report fields (DESIGN.md App. A.2),
// aggregated across shards.
type RunReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests    int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SentRequests     int64                  `protobuf:"varint,2,opt,name=sent_requests,json=sentRequests,proto3" json:"sent_requests,omitempty"`
	FailedRequests   int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	FilteredRequests int64                  `protobuf:"varint,4,opt,name=filtered_requests,json=filteredRequests,proto3" json:"filtered_requests,omitempty"`
	DurationMs       int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AchievedRps      float64                `protobuf:"fixed64,6,opt,name=achieved_rps,json=achievedRps,proto3" json:"achieved_rps,omitempty"`
	MeanLatencyMs    float64                `protobuf:"fixed64,7,opt,name=mean_latency_ms,json=meanLatencyMs,proto3" json:"mean_latency_ms,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,8,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs     float64                `protobuf:"fixed64,9,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,10,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunReport) Reset() {
	*x = RunReport{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunReport) ProtoMessage() {}

func (x *RunReport) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunReport.ProtoReflect.Descriptor instead.
func (*RunReport) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{7}
}

func (x *RunReport) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *RunReport) GetSentRequests() int64 {
	if x != nil {
		return x.SentRequests
	}
	return 0
}

func (x *RunReport) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *RunReport) GetFilteredRequests() int64 {
	if x != nil {
		return x.FilteredRequests
	}
	return 0
}

func (x *RunReport) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunReport) GetAchievedRps() float64 {
	if x != nil {
		return x.AchievedRps
	}
	return 0
}

func (x *RunReport) GetMeanLatencyMs() float64 {
	if x != nil {
		return x.MeanLatencyMs
	}
	return 0
}

func (x *RunReport) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *RunReport) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *RunReport) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Report        *RunReport             `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_loaddriver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_loaddriver_proto_rawDescGZIP(), []int{8}
}

func (x *StopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StopResponse) GetReport() *RunReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_plugin_v1_loaddriver_proto protoreflect.FileDescriptor

const file_plugin_v1_loaddriver_proto_rawDesc = "" +
	"\n" +
	"\x1aplugin/v1/loaddriver.proto\x12\x12parallax.plugin.v1\"2\n" +
	"\vPlanRequest\x12#\n" +
	"\rworkload_json\x18\x01 \x01(\fR\fworkloadJson\"Y\n" +
	"\fPlanResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12!\n" +
	"\ftotal_shards\x18\x03 \x01(\x03R\vtotalShards\"N\n" +
	"\fStartRequest\x12#\n" +
	"\rworkload_json\x18\x01 \x01(\fR\fworkloadJson\x12\x19\n" +
	"\btrial_id\x18\x02 \x01(\tR\atrialId\"@\n" +
	"\rStartResponse\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"'\n" +
	"\fWatchRequest\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\"\xd0\x01\n" +
	"\n" +
	"WatchEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12#\n" +
	"\rsent_requests\x18\x02 \x01(\x03R\fsentRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x12!\n" +
	"\fachieved_rps\x18\x04 \x01(\x01R\vachievedRps\x12\x18\n" +
	"\aaborted\x18\x05 \x01(\bR\aaborted\x12!\n" +
	"\fabort_reason\x18\x06 \x01(\tR\vabortReason\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\arun_ref\x18\x01 \x01(\tR\x06runRef\"\x8b\x03\n" +
	"\tRunReport\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12#\n" +
	"\rsent_requests\x18\x02 \x01(\x03R\fsentRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x12+\n" +
	"\x11filtered_requests\x18\x04 \x01(\x03R\x10filteredRequests\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\fachieved_rps\x18\x06 \x01(\x01R\vachievedRps\x12&\n" +
	"\x0fmean_latency_ms\x18\a \x01(\x01R\rmeanLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\b \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\t \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\n" +
	" \x01(\x01R\fp99LatencyMs\"U\n" +
	"\fStopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x125\n" +
	"\x06report\x18\x02 \x01(\v2\x1d.parallax.plugin.v1.RunReportR\x06report2\xbd\x02\n" +
	"\n" +
	"LoadDriver\x12I\n" +
	"\x04Plan\x12\x1f.parallax.plugin.v1.PlanRequest\x1a .parallax.plugin.v1.PlanResponse\x12L\n" +
	"\x05Start\x12 .parallax.plugin.v1.StartRequest\x1a!.parallax.plugin.v1.StartResponse\x12K\n" +
	"\x05Watch\x12 .parallax.plugin.v1.WatchRequest\x1a\x1e.parallax.plugin.v1.WatchEvent0\x01\x12I\n" +
	"\x04Stop\x12\x1f.parallax.plugin.v1.StopRequest\x1a .parallax.plugin.v1.StopResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_loaddriver_proto_rawDescOnce sync.Once
	file_plugin_v1_loaddriver_proto_rawDescData []byte
)

func file_plugin_v1_loaddriver_proto_rawDescGZIP() []byte {
	file_plugin_v1_loaddriver_proto_rawDescOnce.Do(func() {
		file_plugin_v1_loaddriver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_loaddriver_proto_rawDesc), len(file_plugin_v1_loaddriver_proto_rawDesc)))
	})
	return file_plugin_v1_loaddriver_proto_rawDescData
}

var file_plugin_v1_loaddriver_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_v1_loaddriver_proto_goTypes = []any{
	(*PlanRequest)(nil),   // 0: parallax.plugin.v1.PlanRequest
	(*PlanResponse)(nil),  // 1: parallax.plugin.v1.PlanResponse
	(*StartRequest)(nil),  // 2: parallax.plugin.v1.StartRequest
	(*StartResponse)(nil), // 3: parallax.plugin.v1.StartResponse
	(*WatchRequest)(nil),  // 4: parallax.plugin.v1.WatchRequest
	(*WatchEvent)(nil),    // 5: parallax.plugin.v1.WatchEvent
	(*StopRequest)(nil),   // 6: parallax.plugin.v1.StopRequest
	(*RunReport)(nil),     // 7: parallax.plugin.v1.RunReport
	(*StopResponse)(nil),  // 8: parallax.plugin.v1.StopResponse
}
var file_plugin_v1_loaddriver_proto_depIdxs = []int32{
	7, // 0: parallax.plugin.v1.StopResponse.report:type_name -> parallax.plugin.v1.RunReport
	0, // 1: parallax.plugin.v1.LoadDriver.Plan:input_type -> parallax.plugin.v1.PlanRequest
	2, // 2: parallax.plugin.v1.LoadDriver.Start:input_type -> parallax.plugin.v1.StartRequest
	4, // 3: parallax.plugin.v1.LoadDriver.Watch:input_type -> parallax.plugin.v1.WatchRequest
	6, // 4: parallax.plugin.v1.LoadDriver.Stop:input_type -> parallax.plugin.v1.StopRequest
	1, // 5: parallax.plugin.v1.LoadDriver.Plan:output_type -> parallax.plugin.v1.PlanResponse
	3, // 6: parallax.plugin.v1.LoadDriver.Start:output_type -> parallax.plugin.v1.StartResponse
	5, // 7: parallax.plugin.v1.LoadDriver.Watch:output_type -> parallax.plugin.v1.WatchEvent
	8, // 8: parallax.plugin.v1.LoadDriver.Stop:output_type -> parallax.plugin.v1.StopResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_v1_loaddriver_proto_init() }
func file_plugin_v1_loaddriver_proto_init() {
	if File_plugin_v1_loaddriver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_loaddriver_proto_rawDesc), len(file_plugin_v1_loaddriver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_loaddriver_proto_goTypes,
		DependencyIndexes: file_plugin_v1_loaddriver_proto_depIdxs,
		MessageInfos:      file_plugin_v1_loaddriver_proto_msgTypes,
	}.Build()
	File_plugin_v1_loaddriver_proto = out.File
	file_plugin_v1_loaddriver_proto_goTypes = nil
	file_plugin_v1_loaddriver_proto_depIdxs = nil
}
