// Provider plugins evaluate SLIs over a trial's measurement window (DESIGN.md §5.1,
// §11). provider-prometheus queries PromQL. Each provider defines its own query
// dialect and receives it as an opaque JSON block — the core enumerates no
// dialects (docs/GENERALIZATION.md G6).
// Swap boundary: trial.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Window is the recorded measurement window [t1, t2]. Times are RFC3339 strings so
// the ABI carries no well-known-type dependency; providers cross-check against their
// backend's server clock (DESIGN.md §9, "timestamps are law").
type Window struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T1Rfc3339     string                 `protobuf:"bytes,1,opt,name=t1_rfc3339,json=t1Rfc3339,proto3" json:"t1_rfc3339,omitempty"`
	T2Rfc3339     string                 `protobuf:"bytes,2,opt,name=t2_rfc3339,json=t2Rfc3339,proto3" json:"t2_rfc3339,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_plugin_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Window) GetT1Rfc3339() string {
	if x != nil {
		return x.T1Rfc3339
	}
	return ""
}

func (x *Window) GetT2Rfc3339() string {
	if x != nil {
		return x.T2Rfc3339
	}
	return ""
}

type SLIQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One of the trust classes: fidelity | client | server | derived (§11).
	SliClass string `protobuf:"bytes,2,opt,name=sli_class,json=sliClass,proto3" json:"sli_class,omitempty"`
	// The study's slis[].from.config block, verbatim: PromQL for prometheus, a metric
	// key for runreport, whatever a third-party provider's Describe() schema declares.
	// String values are {{.Window}}-templated by the host before the call.
	ConfigJson    []byte `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLIQuery) Reset() {
	*x = SLIQuery{}
	mi := &file_plugin_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLIQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLIQuery) ProtoMessage() {}

func (x *SLIQuery) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLIQuery.ProtoReflect.Descriptor instead.
func (*SLIQuery) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *SLIQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLIQuery) GetSliClass() string {
	if x != nil {
		return x.SliClass
	}
	return ""
}

func (x *SLIQuery) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type SLIValue struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SliClass string                 `protobuf:"bytes,2,opt,name=sli_class,json=sliClass,proto3" json:"sli_class,omitempty"`
	Value    float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	// The resolved query the provider actually ran, recorded as evidence.
	ResolvedQuery      string `protobuf:"bytes,4,opt,name=resolved_query,json=resolvedQuery,proto3" json:"resolved_query,omitempty"`
	EvaluatedAtRfc3339 string `protobuf:"bytes,5,opt,name=evaluated_at_rfc3339,json=evaluatedAtRfc3339,proto3" json:"evaluated_at_rfc3339,omitempty"`
	Ok                 bool   `protobuf:"varint,6,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail             string `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SLIValue) Reset() {
	*x = SLIValue{}
	mi := &file_plugin_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLIValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLIValue) ProtoMessage() {}

func (x *SLIValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLIValue.ProtoReflect.Descriptor instead.
func (*SLIValue) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *SLIValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLIValue) GetSliClass() string {
	if x != nil {
		return x.SliClass
	}
	return ""
}

func (x *SLIValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SLIValue) GetResolvedQuery() string {
	if x != nil {
		return x.ResolvedQuery
	}
	return ""
}

func (x *SLIValue) GetEvaluatedAtRfc3339() string {
	if x != nil {
		return x.EvaluatedAtRfc3339
	}
	return ""
}

func (x *SLIValue) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SLIValue) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_plugin_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{3}
}

type CapabilitiesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SupportedClasses []string               `protobuf:"bytes,1,rep,name=supported_classes,json=supportedClasses,proto3" json:"supported_classes,omitempty"`
	SupportsSnapshot bool                   `protobuf:"varint,2,opt,name=supports_snapshot,json=supportsSnapshot,proto3" json:"supports_snapshot,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_plugin_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilitiesResponse) GetSupportedClasses() []string {
	if x != nil {
		return x.SupportedClasses
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportsSnapshot() bool {
	if x != nil {
		return x.SupportsSnapshot
	}
	return false
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        *Window                `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	Queries       []*SLIQuery            `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_plugin_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *CollectRequest) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *CollectRequest) GetQueries() []*SLIQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type CollectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*SLIValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_plugin_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *CollectResponse) GetValues() []*SLIValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        *Window                `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_plugin_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotRequest) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri   string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Bytes         int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_plugin_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotResponse) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *SnapshotResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *SnapshotResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

var File_plugin_v1_provider_proto protoreflect.FileDescriptor

const file_plugin_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/v1/provider.proto\x12\x12parallax.plugin.v1\"F\n" +
	"\x06Window\x12\x1d\n" +
	"\n" +
	"t1_rfc3339\x18\x01 \x01(\tR\tt1Rfc3339\x12\x1d\n" +
	"\n" +
	"t2_rfc3339\x18\x02 \x01(\tR\tt2Rfc3339\"\\\n" +
	"\bSLIQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsli_class\x18\x02 \x01(\tR\bsliClass\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\"\xd2\x01\n" +
	"\bSLIValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsli_class\x18\x02 \x01(\tR\bsliClass\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12%\n" +
	"\x0eresolved_query\x18\x04 \x01(\tR\rresolvedQuery\x120\n" +
	"\x14evaluated_at_rfc3339\x18\x05 \x01(\tR\x12evaluatedAtRfc3339\x12\x0e\n" +
	"\x02ok\x18\x06 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\"\x15\n" +
	"\x13CapabilitiesRequest\"p\n" +
	"\x14CapabilitiesResponse\x12+\n" +
	"\x11supported_classes\x18\x01 \x03(\tR\x10supportedClasses\x12+\n" +
	"\x11supports_snapshot\x18\x02 \x01(\bR\x10supportsSnapshot\"|\n" +
	"\x0eCollectRequest\x122\n" +
	"\x06window\x18\x01 \x01(\v2\x1a.parallax.plugin.v1.WindowR\x06window\x126\n" +
	"\aqueries\x18\x02 \x03(\v2\x1c.parallax.plugin.v1.SLIQueryR\aqueries\"G\n" +
	"\x0fCollectResponse\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.parallax.plugin.v1.SLIValueR\x06values\"E\n" +
	"\x0fSnapshotRequest\x122\n" +
	"\x06window\x18\x01 \x01(\v2\x1a.parallax.plugin.v1.WindowR\x06window\"c\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes2\x98\x02\n" +
	"\bProvider\x12a\n" +
	"\fCapabilities\x12'.parallax.plugin.v1.CapabilitiesRequest\x1a(.parallax.plugin.v1.CapabilitiesResponse\x12R\n" +
	"\aCollect\x12\".parallax.plugin.v1.CollectRequest\x1a#.parallax.plugin.v1.CollectResponse\x12U\n" +
	"\bSnapshot\x12#.parallax.plugin.v1.SnapshotRequest\x1a$.parallax.plugin.v1.SnapshotResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_provider_proto_rawDescOnce sync.Once
	file_plugin_v1_provider_proto_rawDescData []byte
)

func file_plugin_v1_provider_proto_rawDescGZIP() []byte {
	file_plugin_v1_provider_proto_rawDescOnce.Do(func() {
		file_plugin_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_provider_proto_rawDesc), len(file_plugin_v1_provider_proto_rawDesc)))
	})
	return file_plugin_v1_provider_proto_rawDescData
}

var file_plugin_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_v1_provider_proto_goTypes = []any{
	(*Window)(nil),               // 0: parallax.plugin.v1.Window
	(*SLIQuery)(nil),             // 1: parallax.plugin.v1.SLIQuery
	(*SLIValue)(nil),             // 2: parallax.plugin.v1.SLIValue
	(*CapabilitiesRequest)(nil),  // 3: parallax.plugin.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 4: parallax.plugin.v1.CapabilitiesResponse
	(*CollectRequest)(nil),       // 5: parallax.plugin.v1.CollectRequest
	(*CollectResponse)(nil),      // 6: parallax.plugin.v1.CollectResponse
	(*SnapshotRequest)(nil),      // 7: parallax.plugin.v1.SnapshotRequest
	(*SnapshotResponse)(nil),     // 8: parallax.plugin.v1.SnapshotResponse
}
var file_plugin_v1_provider_proto_depIdxs = []int32{
	0, // 0: parallax.plugin.v1.CollectRequest.window:type_name -> parallax.plugin.v1.Window
	1, // 1: parallax.plugin.v1.CollectRequest.queries:type_name -> parallax.plugin.v1.SLIQuery
	2, // 2: parallax.plugin.v1.CollectResponse.values:type_name -> parallax.plugin.v1.SLIValue
	0, // 3: parallax.plugin.v1.SnapshotRequest.window:type_name -> parallax.plugin.v1.Window
	3, // 4: parallax.plugin.v1.Provider.Capabilities:input_type -> parallax.plugin.v1.CapabilitiesRequest
	5, // 5: parallax.plugin.v1.Provider.Collect:input_type -> parallax.plugin.v1.CollectRequest
	7, // 6: parallax.plugin.v1.Provider.Snapshot:input_type -> parallax.plugin.v1.SnapshotRequest
	4, // 7: parallax.plugin.v1.Provider.Capabilities:output_type -> parallax.plugin.v1.CapabilitiesResponse
	6, // 8: parallax.plugin.v1.Provider.Collect:output_type -> parallax.plugin.v1.CollectResponse
	8, // 9: parallax.plugin.v1.Provider.Snapshot:output_type -> parallax.plugin.v1.SnapshotResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_v1_provider_proto_init() }
func file_plugin_v1_provider_proto_init() {
	if File_plugin_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_provider_proto_rawDesc), len(file_plugin_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_provider_proto_goTypes,
		DependencyIndexes: file_plugin_v1_provider_proto_depIdxs,
		MessageInfos:      file_plugin_v1_provider_proto_msgTypes,
	}.Build()
	File_plugin_v1_provider_proto = out.File
	file_plugin_v1_provider_proto_goTypes = nil
	file_plugin_v1_provider_proto_depIdxs = nil
}
