// Scenario plugins inject faults during validation experiments (DESIGN.md §5.1,
// §13.3): pod-kill, netpol-outage, rate-burst, hpa-ramp. Swap boundary: trial.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugin/v1/scenario.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scenario_Inject_FullMethodName = "/parallax.plugin.v1.Scenario/Inject"
	Scenario_Verify_FullMethodName = "/parallax.plugin.v1.Scenario/Verify"
	Scenario_Revert_FullMethodName = "/parallax.plugin.v1.Scenario/Revert"
)

// ScenarioClient is the client API for Scenario service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScenarioClient interface {
	// Inject begins the fault and streams lifecycle events until injected.
	Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error)
	// Verify asserts the scenario's success/health predicates.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// Revert restores the pre-scenario state (idempotent).
	Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error)
}

type scenarioClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioClient(cc grpc.ClientConnInterface) ScenarioClient {
	return &scenarioClient{cc}
}

func (c *scenarioClient) Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scenario_ServiceDesc.Streams[0], Scenario_Inject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InjectRequest, ScenarioEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scenario_InjectClient = grpc.ServerStreamingClient[ScenarioEvent]

func (c *scenarioClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, Scenario_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioClient) Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertResponse)
	err := c.cc.Invoke(ctx, Scenario_Revert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScenarioServer is the server API for Scenario service.
// All implementations must embed UnimplementedScenarioServer
// for forward compatibility.
type ScenarioServer interface {
	// Inject begins the fault and streams lifecycle events until injected.
	Inject(*InjectRequest, grpc.ServerStreamingServer[ScenarioEvent]) error
	// Verify asserts the scenario's success/health predicates.
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// Revert restores the pre-scenario state (idempotent).
	Revert(context.Context, *RevertRequest) (*RevertResponse, error)
	mustEmbedUnimplementedScenarioServer()
}

// UnimplementedScenarioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioServer struct{}

func (UnimplementedScenarioServer) Inject(*InjectRequest, grpc.ServerStreamingServer[ScenarioEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Inject not implemented")
}
func (UnimplementedScenarioServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedScenarioServer) Revert(context.Context, *RevertRequest) (*RevertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revert not implemented")
}
func (UnimplementedScenarioServer) mustEmbedUnimplementedScenarioServer() {}
func (UnimplementedScenarioServer) testEmbeddedByValue()                  {}

// UnsafeScenarioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioServer will
// result in compilation errors.
type UnsafeScenarioServer interface {
	mustEmbedUnimplementedScenarioServer()
}

func RegisterScenarioServer(s grpc.ServiceRegistrar, srv ScenarioServer) {
	// If the following call pancis, it indicates UnimplementedScenarioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scenario_ServiceDesc, srv)
}

func _Scenario_Inject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScenarioServer).Inject(m, &grpc.GenericServerStream[InjectRequest, ScenarioEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scenario_InjectServer = grpc.ServerStreamingServer[ScenarioEvent]

func _Scenario_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scenario_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenario_Revert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServer).Revert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scenario_Revert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServer).Revert(ctx, req.(*RevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scenario_ServiceDesc is the grpc.ServiceDesc for Scenario service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scenario_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.plugin.v1.Scenario",
	HandlerType: (*ScenarioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _Scenario_Verify_Handler,
		},
		{
			MethodName: "Revert",
			Handler:    _Scenario_Revert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Inject",
			Handler:       _Scenario_Inject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/v1/scenario.proto",
}
