// Scenario plugins inject faults during validation experiments (DESIGN.md §5.1,
// §13.3): pod-kill, netpol-outage, rate-burst, hpa-ramp. Swap boundary: trial.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/scenario.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	TrialId       string                 `protobuf:"bytes,2,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRequest) Reset() {
	*x = InjectRequest{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRequest) ProtoMessage() {}

func (x *InjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRequest.ProtoReflect.Descriptor instead.
func (*InjectRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *InjectRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *InjectRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type ScenarioEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	AtUnixNano    int64                  `protobuf:"varint,3,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioEvent) Reset() {
	*x = ScenarioEvent{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioEvent) ProtoMessage() {}

func (x *ScenarioEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioEvent.ProtoReflect.Descriptor instead.
func (*ScenarioEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ScenarioEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ScenarioEvent) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrialId       string                 `protobuf:"bytes,1,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	VerdictJson   []byte                 `protobuf:"bytes,2,opt,name=verdict_json,json=verdictJson,proto3" json:"verdict_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyResponse) GetVerdictJson() []byte {
	if x != nil {
		return x.VerdictJson
	}
	return nil
}

type RevertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrialId       string                 `protobuf:"bytes,1,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertRequest) Reset() {
	*x = RevertRequest{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertRequest) ProtoMessage() {}

func (x *RevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertRequest.ProtoReflect.Descriptor instead.
func (*RevertRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *RevertRequest) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

type RevertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertResponse) Reset() {
	*x = RevertResponse{}
	mi := &file_plugin_v1_scenario_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertResponse) ProtoMessage() {}

func (x *RevertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_scenario_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertResponse.ProtoReflect.Descriptor instead.
func (*RevertResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_scenario_proto_rawDescGZIP(), []int{5}
}

func (x *RevertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RevertResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_plugin_v1_scenario_proto protoreflect.FileDescriptor

const file_plugin_v1_scenario_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/v1/scenario.proto\x12\x12parallax.plugin.v1\"K\n" +
	"\rInjectRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x19\n" +
	"\btrial_id\x18\x02 \x01(\tR\atrialId\"_\n" +
	"\rScenarioEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12 \n" +
	"\fat_unix_nano\x18\x03 \x01(\x03R\n" +
	"atUnixNano\"*\n" +
	"\rVerifyRequest\x12\x19\n" +
	"\btrial_id\x18\x01 \x01(\tR\atrialId\"C\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fverdict_json\x18\x02 \x01(\fR\vverdictJson\"*\n" +
	"\rRevertRequest\x12\x19\n" +
	"\btrial_id\x18\x01 \x01(\tR\atrialId\"8\n" +
	"\x0eRevertResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail2\xfe\x01\n" +
	"\bScenario\x12P\n" +
	"\x06Inject\x12!.parallax.plugin.v1.InjectRequest\x1a!.parallax.plugin.v1.ScenarioEvent0\x01\x12O\n" +
	"\x06Verify\x12!.parallax.plugin.v1.VerifyRequest\x1a\".parallax.plugin.v1.VerifyResponse\x12O\n" +
	"\x06Revert\x12!.parallax.plugin.v1.RevertRequest\x1a\".parallax.plugin.v1.RevertResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_scenario_proto_rawDescOnce sync.Once
	file_plugin_v1_scenario_proto_rawDescData []byte
)

func file_plugin_v1_scenario_proto_rawDescGZIP() []byte {
	file_plugin_v1_scenario_proto_rawDescOnce.Do(func() {
		file_plugin_v1_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_scenario_proto_rawDesc), len(file_plugin_v1_scenario_proto_rawDesc)))
	})
	return file_plugin_v1_scenario_proto_rawDescData
}

var file_plugin_v1_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_v1_scenario_proto_goTypes = []any{
	(*InjectRequest)(nil),  // 0: parallax.plugin.v1.InjectRequest
	(*ScenarioEvent)(nil),  // 1: parallax.plugin.v1.ScenarioEvent
	(*VerifyRequest)(nil),  // 2: parallax.plugin.v1.VerifyRequest
	(*VerifyResponse)(nil), // 3: parallax.plugin.v1.VerifyResponse
	(*RevertRequest)(nil),  // 4: parallax.plugin.v1.RevertRequest
	(*RevertResponse)(nil), // 5: parallax.plugin.v1.RevertResponse
}
var file_plugin_v1_scenario_proto_depIdxs = []int32{
	0, // 0: parallax.plugin.v1.Scenario.Inject:input_type -> parallax.plugin.v1.InjectRequest
	2, // 1: parallax.plugin.v1.Scenario.Verify:input_type -> parallax.plugin.v1.VerifyRequest
	4, // 2: parallax.plugin.v1.Scenario.Revert:input_type -> parallax.plugin.v1.RevertRequest
	1, // 3: parallax.plugin.v1.Scenario.Inject:output_type -> parallax.plugin.v1.ScenarioEvent
	3, // 4: parallax.plugin.v1.Scenario.Verify:output_type -> parallax.plugin.v1.VerifyResponse
	5, // 5: parallax.plugin.v1.Scenario.Revert:output_type -> parallax.plugin.v1.RevertResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_v1_scenario_proto_init() }
func file_plugin_v1_scenario_proto_init() {
	if File_plugin_v1_scenario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_scenario_proto_rawDesc), len(file_plugin_v1_scenario_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_scenario_proto_goTypes,
		DependencyIndexes: file_plugin_v1_scenario_proto_depIdxs,
		MessageInfos:      file_plugin_v1_scenario_proto_msgTypes,
	}.Build()
	File_plugin_v1_scenario_proto = out.File
	file_plugin_v1_scenario_proto_goTypes = nil
	file_plugin_v1_scenario_proto_depIdxs = nil
}
