// Strategy plugins drive the search: Init(space, budget) then repeated Ask/Tell,
// with Report for anytime curves (DESIGN.md §5.1, §14). Swap boundary: between
// ask/tell calls.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/strategy.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search space (dimensions + constraints) serialized as JSON (§8 space block).
	SpaceJson []byte `protobuf:"bytes,1,opt,name=space_json,json=spaceJson,proto3" json:"space_json,omitempty"`
	// Budget currencies (maxTrials / maxClusterTime / maxWallClock) as JSON.
	BudgetJson    []byte `protobuf:"bytes,2,opt,name=budget_json,json=budgetJson,proto3" json:"budget_json,omitempty"`
	Seed          int64  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetSpaceJson() []byte {
	if x != nil {
		return x.SpaceJson
	}
	return nil
}

func (x *InitRequest) GetBudgetJson() []byte {
	if x != nil {
		return x.BudgetJson
	}
	return nil
}

func (x *InitRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Suggestion struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Dimension path → chosen value.
	Assignments   map[string]string `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *Suggestion) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *Suggestion) GetAssignments() map[string]string {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *AskRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *AskResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type TellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash    string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Objective     float64                `protobuf:"fixed64,2,opt,name=objective,proto3" json:"objective,omitempty"`
	Feasible      bool                   `protobuf:"varint,3,opt,name=feasible,proto3" json:"feasible,omitempty"`
	MetricsJson   []byte                 `protobuf:"bytes,4,opt,name=metrics_json,json=metricsJson,proto3" json:"metrics_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TellRequest) Reset() {
	*x = TellRequest{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellRequest) ProtoMessage() {}

func (x *TellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellRequest.ProtoReflect.Descriptor instead.
func (*TellRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *TellRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *TellRequest) GetObjective() float64 {
	if x != nil {
		return x.Objective
	}
	return 0
}

func (x *TellRequest) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *TellRequest) GetMetricsJson() []byte {
	if x != nil {
		return x.MetricsJson
	}
	return nil
}

type TellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TellResponse) Reset() {
	*x = TellResponse{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellResponse) ProtoMessage() {}

func (x *TellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellResponse.ProtoReflect.Descriptor instead.
func (*TellResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *TellResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{7}
}

type ReportResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ReportJson []byte                 `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	// True when the strategy has exhausted its budget / converged.
	Done          bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

func (x *ReportResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_plugin_v1_strategy_proto protoreflect.FileDescriptor

const file_plugin_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/v1/strategy.proto\x12\x12parallax.plugin.v1\"a\n" +
	"\vInitRequest\x12\x1d\n" +
	"\n" +
	"space_json\x18\x01 \x01(\fR\tspaceJson\x12\x1f\n" +
	"\vbudget_json\x18\x02 \x01(\fR\n" +
	"budgetJson\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\"6\n" +
	"\fInitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xc0\x01\n" +
	"\n" +
	"Suggestion\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12Q\n" +
	"\vassignments\x18\x02 \x03(\v2/.parallax.plugin.v1.Suggestion.AssignmentsEntryR\vassignments\x1a>\n" +
	"\x10AssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"AskRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"O\n" +
	"\vAskResponse\x12@\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1e.parallax.plugin.v1.SuggestionR\vsuggestions\"\x8b\x01\n" +
	"\vTellRequest\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12\x1c\n" +
	"\tobjective\x18\x02 \x01(\x01R\tobjective\x12\x1a\n" +
	"\bfeasible\x18\x03 \x01(\bR\bfeasible\x12!\n" +
	"\fmetrics_json\x18\x04 \x01(\fR\vmetricsJson\"\x1e\n" +
	"\fTellResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x0f\n" +
	"\rReportRequest\"E\n" +
	"\x0eReportResponse\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\fR\n" +
	"reportJson\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done2\xb9\x02\n" +
	"\bStrategy\x12I\n" +
	"\x04Init\x12\x1f.parallax.plugin.v1.InitRequest\x1a .parallax.plugin.v1.InitResponse\x12F\n" +
	"\x03Ask\x12\x1e.parallax.plugin.v1.AskRequest\x1a\x1f.parallax.plugin.v1.AskResponse\x12I\n" +
	"\x04Tell\x12\x1f.parallax.plugin.v1.TellRequest\x1a .parallax.plugin.v1.TellResponse\x12O\n" +
	"\x06Report\x12!.parallax.plugin.v1.ReportRequest\x1a\".parallax.plugin.v1.ReportResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_strategy_proto_rawDescOnce sync.Once
	file_plugin_v1_strategy_proto_rawDescData []byte
)

func file_plugin_v1_strategy_proto_rawDescGZIP() []byte {
	file_plugin_v1_strategy_proto_rawDescOnce.Do(func() {
		file_plugin_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_strategy_proto_rawDesc), len(file_plugin_v1_strategy_proto_rawDesc)))
	})
	return file_plugin_v1_strategy_proto_rawDescData
}

var file_plugin_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_v1_strategy_proto_goTypes = []any{
	(*InitRequest)(nil),    // 0: parallax.plugin.v1.InitRequest
	(*InitResponse)(nil),   // 1: parallax.plugin.v1.InitResponse
	(*Suggestion)(nil),     // 2: parallax.plugin.v1.Suggestion
	(*AskRequest)(nil),     // 3: parallax.plugin.v1.AskRequest
	(*AskResponse)(nil),    // 4: parallax.plugin.v1.AskResponse
	(*TellRequest)(nil),    // 5: parallax.plugin.v1.TellRequest
	(*TellResponse)(nil),   // 6: parallax.plugin.v1.TellResponse
	(*ReportRequest)(nil),  // 7: parallax.plugin.v1.ReportRequest
	(*ReportResponse)(nil), // 8: parallax.plugin.v1.ReportResponse
	nil,                    // 9: parallax.plugin.v1.Suggestion.AssignmentsEntry
}
var file_plugin_v1_strategy_proto_depIdxs = []int32{
	9, // 0: parallax.plugin.v1.Suggestion.assignments:type_name -> parallax.plugin.v1.Suggestion.AssignmentsEntry
	2, // 1: parallax.plugin.v1.AskResponse.suggestions:type_name -> parallax.plugin.v1.Suggestion
	0, // 2: parallax.plugin.v1.Strategy.Init:input_type -> parallax.plugin.v1.InitRequest
	3, // 3: parallax.plugin.v1.Strategy.Ask:input_type -> parallax.plugin.v1.AskRequest
	5, // 4: parallax.plugin.v1.Strategy.Tell:input_type -> parallax.plugin.v1.TellRequest
	7, // 5: parallax.plugin.v1.Strategy.Report:input_type -> parallax.plugin.v1.ReportRequest
	1, // 6: parallax.plugin.v1.Strategy.Init:output_type -> parallax.plugin.v1.InitResponse
	4, // 7: parallax.plugin.v1.Strategy.Ask:output_type -> parallax.plugin.v1.AskResponse
	6, // 8: parallax.plugin.v1.Strategy.Tell:output_type -> parallax.plugin.v1.TellResponse
	8, // 9: parallax.plugin.v1.Strategy.Report:output_type -> parallax.plugin.v1.ReportResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_strategy_proto_init() }
func file_plugin_v1_strategy_proto_init() {
	if File_plugin_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_strategy_proto_rawDesc), len(file_plugin_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_strategy_proto_goTypes,
		DependencyIndexes: file_plugin_v1_strategy_proto_depIdxs,
		MessageInfos:      file_plugin_v1_strategy_proto_msgTypes,
	}.Build()
	File_plugin_v1_strategy_proto = out.File
	file_plugin_v1_strategy_proto_goTypes = nil
	file_plugin_v1_strategy_proto_depIdxs = nil
}
