// Strategy plugins drive the search: given the space, the budget, and everything
// observed so far, suggest the next batch of config points (DESIGN.md §5.1, §14).
//
// Ask is a *pure function* of its request. A strategy holds no session state across
// calls, and the host passes the full observation history every time. That is not a
// stylistic choice: the plugin host hot-reloads plugins with drain-and-swap (§5.4)
// and one plugin process serves every study in the cluster, so per-session state in
// the plugin would be lost on reload and cross-contaminated between concurrent
// studies. Stateless Ask also means a study resumes from the results DB exactly
// where it left off, because the DB *is* the history (docs/GENERALIZATION.md G3).
//
// The evaluation loop stays in the Study controller — a strategy suggests, it never
// decides how many trials get spent (§14).
//
// Swap boundary: between Ask calls.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/strategy.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Observation is one evaluated config point: what was tried, and how it scored.
type Observation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Dimension name → chosen value, as suggested.
	Assignments map[string]string `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The study's primary objective, already normalized to "lower is better" so a
	// strategy never has to read the study's direction.
	Objective float64 `protobuf:"fixed64,3,opt,name=objective,proto3" json:"objective,omitempty"`
	// False when a guardrail was breached or the trial was invalid; infeasible points
	// still inform the search (that region is bad) but are never optima.
	Feasible bool `protobuf:"varint,4,opt,name=feasible,proto3" json:"feasible,omitempty"`
	// Measurement window in seconds — the fidelity dial multi-fidelity strategies
	// (ASHA and friends) rung on.
	FidelitySeconds float64 `protobuf:"fixed64,5,opt,name=fidelity_seconds,json=fidelitySeconds,proto3" json:"fidelity_seconds,omitempty"`
	Rep             int32   `protobuf:"varint,6,opt,name=rep,proto3" json:"rep,omitempty"`
	// Wall-clock cost of evaluating this point, for cost-aware strategies.
	CostSeconds float64 `protobuf:"fixed64,7,opt,name=cost_seconds,json=costSeconds,proto3" json:"cost_seconds,omitempty"`
	// All SLI values for the point, for strategies that model more than the objective.
	MetricsJson   []byte `protobuf:"bytes,8,opt,name=metrics_json,json=metricsJson,proto3" json:"metrics_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Observation) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *Observation) GetAssignments() map[string]string {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *Observation) GetObjective() float64 {
	if x != nil {
		return x.Objective
	}
	return 0
}

func (x *Observation) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *Observation) GetFidelitySeconds() float64 {
	if x != nil {
		return x.FidelitySeconds
	}
	return 0
}

func (x *Observation) GetRep() int32 {
	if x != nil {
		return x.Rep
	}
	return 0
}

func (x *Observation) GetCostSeconds() float64 {
	if x != nil {
		return x.CostSeconds
	}
	return 0
}

func (x *Observation) GetMetricsJson() []byte {
	if x != nil {
		return x.MetricsJson
	}
	return nil
}

type AskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search space (dimensions + constraints) serialized as JSON (§8 space block).
	SpaceJson []byte `protobuf:"bytes,1,opt,name=space_json,json=spaceJson,proto3" json:"space_json,omitempty"`
	// Budget currencies (maxTrials / maxClusterTime / maxWallClock) as JSON.
	BudgetJson []byte `protobuf:"bytes,2,opt,name=budget_json,json=budgetJson,proto3" json:"budget_json,omitempty"`
	// Run seed. Identical (seed, observations) must yield identical suggestions.
	Seed int64 `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	// How many points the controller wants. A strategy may return fewer.
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Every point observed for this run so far.
	Observations []*Observation `protobuf:"bytes,5,rep,name=observations,proto3" json:"observations,omitempty"`
	// Config hashes already materialized as trials but not yet observed. A strategy
	// must not re-suggest these, and may use them to spread out an in-flight batch.
	Pending []string `protobuf:"bytes,6,rep,name=pending,proto3" json:"pending,omitempty"`
	// The strategy's own config block from the study's space.strategy.config.
	ConfigJson    []byte `protobuf:"bytes,7,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *AskRequest) GetSpaceJson() []byte {
	if x != nil {
		return x.SpaceJson
	}
	return nil
}

func (x *AskRequest) GetBudgetJson() []byte {
	if x != nil {
		return x.BudgetJson
	}
	return nil
}

func (x *AskRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *AskRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AskRequest) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *AskRequest) GetPending() []string {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *AskRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type Suggestion struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Dimension name → chosen value.
	Assignments   map[string]string `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *Suggestion) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *Suggestion) GetAssignments() map[string]string {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type AskResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Suggestions []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	// Done reports that the strategy has exhausted its space or converged. The
	// controller stops sweeping; an empty suggestion list alone does not mean done,
	// since a strategy may simply be waiting on in-flight results.
	Done          bool   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_plugin_v1_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *AskResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AskResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *AskResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_plugin_v1_strategy_proto protoreflect.FileDescriptor

const file_plugin_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/v1/strategy.proto\x12\x12parallax.plugin.v1\"\xff\x02\n" +
	"\vObservation\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12R\n" +
	"\vassignments\x18\x02 \x03(\v20.parallax.plugin.v1.Observation.AssignmentsEntryR\vassignments\x12\x1c\n" +
	"\tobjective\x18\x03 \x01(\x01R\tobjective\x12\x1a\n" +
	"\bfeasible\x18\x04 \x01(\bR\bfeasible\x12)\n" +
	"\x10fidelity_seconds\x18\x05 \x01(\x01R\x0ffidelitySeconds\x12\x10\n" +
	"\x03rep\x18\x06 \x01(\x05R\x03rep\x12!\n" +
	"\fcost_seconds\x18\a \x01(\x01R\vcostSeconds\x12!\n" +
	"\fmetrics_json\x18\b \x01(\fR\vmetricsJson\x1a>\n" +
	"\x10AssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\n" +
	"AskRequest\x12\x1d\n" +
	"\n" +
	"space_json\x18\x01 \x01(\fR\tspaceJson\x12\x1f\n" +
	"\vbudget_json\x18\x02 \x01(\fR\n" +
	"budgetJson\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12C\n" +
	"\fobservations\x18\x05 \x03(\v2\x1f.parallax.plugin.v1.ObservationR\fobservations\x12\x18\n" +
	"\apending\x18\x06 \x03(\tR\apending\x12\x1f\n" +
	"\vconfig_json\x18\a \x01(\fR\n" +
	"configJson\"\xc0\x01\n" +
	"\n" +
	"Suggestion\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12Q\n" +
	"\vassignments\x18\x02 \x03(\v2/.parallax.plugin.v1.Suggestion.AssignmentsEntryR\vassignments\x1a>\n" +
	"\x10AssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\vAskResponse\x12@\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1e.parallax.plugin.v1.SuggestionR\vsuggestions\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2R\n" +
	"\bStrategy\x12F\n" +
	"\x03Ask\x12\x1e.parallax.plugin.v1.AskRequest\x1a\x1f.parallax.plugin.v1.AskResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_strategy_proto_rawDescOnce sync.Once
	file_plugin_v1_strategy_proto_rawDescData []byte
)

func file_plugin_v1_strategy_proto_rawDescGZIP() []byte {
	file_plugin_v1_strategy_proto_rawDescOnce.Do(func() {
		file_plugin_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_strategy_proto_rawDesc), len(file_plugin_v1_strategy_proto_rawDesc)))
	})
	return file_plugin_v1_strategy_proto_rawDescData
}

var file_plugin_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_v1_strategy_proto_goTypes = []any{
	(*Observation)(nil), // 0: parallax.plugin.v1.Observation
	(*AskRequest)(nil),  // 1: parallax.plugin.v1.AskRequest
	(*Suggestion)(nil),  // 2: parallax.plugin.v1.Suggestion
	(*AskResponse)(nil), // 3: parallax.plugin.v1.AskResponse
	nil,                 // 4: parallax.plugin.v1.Observation.AssignmentsEntry
	nil,                 // 5: parallax.plugin.v1.Suggestion.AssignmentsEntry
}
var file_plugin_v1_strategy_proto_depIdxs = []int32{
	4, // 0: parallax.plugin.v1.Observation.assignments:type_name -> parallax.plugin.v1.Observation.AssignmentsEntry
	0, // 1: parallax.plugin.v1.AskRequest.observations:type_name -> parallax.plugin.v1.Observation
	5, // 2: parallax.plugin.v1.Suggestion.assignments:type_name -> parallax.plugin.v1.Suggestion.AssignmentsEntry
	2, // 3: parallax.plugin.v1.AskResponse.suggestions:type_name -> parallax.plugin.v1.Suggestion
	1, // 4: parallax.plugin.v1.Strategy.Ask:input_type -> parallax.plugin.v1.AskRequest
	3, // 5: parallax.plugin.v1.Strategy.Ask:output_type -> parallax.plugin.v1.AskResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_v1_strategy_proto_init() }
func file_plugin_v1_strategy_proto_init() {
	if File_plugin_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_strategy_proto_rawDesc), len(file_plugin_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_strategy_proto_goTypes,
		DependencyIndexes: file_plugin_v1_strategy_proto_depIdxs,
		MessageInfos:      file_plugin_v1_strategy_proto_msgTypes,
	}.Build()
	File_plugin_v1_strategy_proto = out.File
	file_plugin_v1_strategy_proto_goTypes = nil
	file_plugin_v1_strategy_proto_depIdxs = nil
}
