// Target plugins own the system-under-test: they apply a config point, gate on
// health, and reset between trials (DESIGN.md §5.1). Swap boundary: trial.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/target.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_plugin_v1_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_plugin_v1_target_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PrepareResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// DimensionAssignment is one resolved axis of a config point, carrying the target
// config location the study mapped it to (docs/GENERALIZATION.md G4).
type DimensionAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimension name as written in the study's space block.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Chosen value for this trial, rendered as a string.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Target config location: a Helm value path, a JSON pointer, a flag name. Defaults
	// to name when the study omits it.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Richer target-defined mapping for axes a single path cannot express.
	MappingJson   []byte `protobuf:"bytes,4,opt,name=mapping_json,json=mappingJson,proto3" json:"mapping_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionAssignment) Reset() {
	*x = DimensionAssignment{}
	mi := &file_plugin_v1_target_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionAssignment) ProtoMessage() {}

func (x *DimensionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionAssignment.ProtoReflect.Descriptor instead.
func (*DimensionAssignment) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{2}
}

func (x *DimensionAssignment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DimensionAssignment) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DimensionAssignment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DimensionAssignment) GetMappingJson() []byte {
	if x != nil {
		return x.MappingJson
	}
	return nil
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash    string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Assignments   []*DimensionAssignment `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	RawConfigJson []byte                 `protobuf:"bytes,3,opt,name=raw_config_json,json=rawConfigJson,proto3" json:"raw_config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_plugin_v1_target_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ApplyRequest) GetAssignments() []*DimensionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ApplyRequest) GetRawConfigJson() []byte {
	if x != nil {
		return x.RawConfigJson
	}
	return nil
}

type ApplyResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Applied bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Detail  string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// References to rolled-out objects (for provenance / cleanup).
	RolledOutRefs []string `protobuf:"bytes,3,rep,name=rolled_out_refs,json=rolledOutRefs,proto3" json:"rolled_out_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_plugin_v1_target_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ApplyResponse) GetRolledOutRefs() []string {
	if x != nil {
		return x.RolledOutRefs
	}
	return nil
}

type ReadyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash     string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_plugin_v1_target_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{5}
}

func (x *ReadyRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ReadyRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_plugin_v1_target_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{6}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ResetRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// When true, force cold starts (restart pods, clear storage prefix) — §9.
	ColdStart     bool `protobuf:"varint,2,opt,name=cold_start,json=coldStart,proto3" json:"cold_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_plugin_v1_target_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{7}
}

func (x *ResetRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ResetRequest) GetColdStart() bool {
	if x != nil {
		return x.ColdStart
	}
	return false
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_plugin_v1_target_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{8}
}

func (x *ResetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResetResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ContractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The study's declared axes (values unset — this is an admission-time check).
	Dimensions    []*DimensionAssignment `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	mi := &file_plugin_v1_target_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{9}
}

func (x *ContractRequest) GetDimensions() []*DimensionAssignment {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type ContractResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UnknownDimensions []string               `protobuf:"bytes,2,rep,name=unknown_dimensions,json=unknownDimensions,proto3" json:"unknown_dimensions,omitempty"`
	// Modes this target supports for the given dimensions (e.g. direct, integrated).
	SupportedModes []string `protobuf:"bytes,3,rep,name=supported_modes,json=supportedModes,proto3" json:"supported_modes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_plugin_v1_target_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_target_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_target_proto_rawDescGZIP(), []int{10}
}

func (x *ContractResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ContractResponse) GetUnknownDimensions() []string {
	if x != nil {
		return x.UnknownDimensions
	}
	return nil
}

func (x *ContractResponse) GetSupportedModes() []string {
	if x != nil {
		return x.SupportedModes
	}
	return nil
}

var File_plugin_v1_target_proto protoreflect.FileDescriptor

const file_plugin_v1_target_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/target.proto\x12\x12parallax.plugin.v1\"1\n" +
	"\x0ePrepareRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"?\n" +
	"\x0fPrepareResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"v\n" +
	"\x13DimensionAssignment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fmapping_json\x18\x04 \x01(\fR\vmappingJson\"\xa2\x01\n" +
	"\fApplyRequest\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12I\n" +
	"\vassignments\x18\x02 \x03(\v2'.parallax.plugin.v1.DimensionAssignmentR\vassignments\x12&\n" +
	"\x0fraw_config_json\x18\x03 \x01(\fR\rrawConfigJson\"i\n" +
	"\rApplyResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12&\n" +
	"\x0frolled_out_refs\x18\x03 \x03(\tR\rrolledOutRefs\"X\n" +
	"\fReadyRequest\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x03R\x0etimeoutSeconds\"=\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"N\n" +
	"\fResetRequest\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12\x1d\n" +
	"\n" +
	"cold_start\x18\x02 \x01(\bR\tcoldStart\"7\n" +
	"\rResetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"Z\n" +
	"\x0fContractRequest\x12G\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v2'.parallax.plugin.v1.DimensionAssignmentR\n" +
	"dimensions\"z\n" +
	"\x10ContractResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12-\n" +
	"\x12unknown_dimensions\x18\x02 \x03(\tR\x11unknownDimensions\x12'\n" +
	"\x0fsupported_modes\x18\x03 \x03(\tR\x0esupportedModes2\x9d\x03\n" +
	"\x06Target\x12R\n" +
	"\aPrepare\x12\".parallax.plugin.v1.PrepareRequest\x1a#.parallax.plugin.v1.PrepareResponse\x12L\n" +
	"\x05Apply\x12 .parallax.plugin.v1.ApplyRequest\x1a!.parallax.plugin.v1.ApplyResponse\x12L\n" +
	"\x05Ready\x12 .parallax.plugin.v1.ReadyRequest\x1a!.parallax.plugin.v1.ReadyResponse\x12L\n" +
	"\x05Reset\x12 .parallax.plugin.v1.ResetRequest\x1a!.parallax.plugin.v1.ResetResponse\x12U\n" +
	"\bContract\x12#.parallax.plugin.v1.ContractRequest\x1a$.parallax.plugin.v1.ContractResponseB7Z5github.com/aburan28/parallax/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_target_proto_rawDescOnce sync.Once
	file_plugin_v1_target_proto_rawDescData []byte
)

func file_plugin_v1_target_proto_rawDescGZIP() []byte {
	file_plugin_v1_target_proto_rawDescOnce.Do(func() {
		file_plugin_v1_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_target_proto_rawDesc), len(file_plugin_v1_target_proto_rawDesc)))
	})
	return file_plugin_v1_target_proto_rawDescData
}

var file_plugin_v1_target_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plugin_v1_target_proto_goTypes = []any{
	(*PrepareRequest)(nil),      // 0: parallax.plugin.v1.PrepareRequest
	(*PrepareResponse)(nil),     // 1: parallax.plugin.v1.PrepareResponse
	(*DimensionAssignment)(nil), // 2: parallax.plugin.v1.DimensionAssignment
	(*ApplyRequest)(nil),        // 3: parallax.plugin.v1.ApplyRequest
	(*ApplyResponse)(nil),       // 4: parallax.plugin.v1.ApplyResponse
	(*ReadyRequest)(nil),        // 5: parallax.plugin.v1.ReadyRequest
	(*ReadyResponse)(nil),       // 6: parallax.plugin.v1.ReadyResponse
	(*ResetRequest)(nil),        // 7: parallax.plugin.v1.ResetRequest
	(*ResetResponse)(nil),       // 8: parallax.plugin.v1.ResetResponse
	(*ContractRequest)(nil),     // 9: parallax.plugin.v1.ContractRequest
	(*ContractResponse)(nil),    // 10: parallax.plugin.v1.ContractResponse
}
var file_plugin_v1_target_proto_depIdxs = []int32{
	2,  // 0: parallax.plugin.v1.ApplyRequest.assignments:type_name -> parallax.plugin.v1.DimensionAssignment
	2,  // 1: parallax.plugin.v1.ContractRequest.dimensions:type_name -> parallax.plugin.v1.DimensionAssignment
	0,  // 2: parallax.plugin.v1.Target.Prepare:input_type -> parallax.plugin.v1.PrepareRequest
	3,  // 3: parallax.plugin.v1.Target.Apply:input_type -> parallax.plugin.v1.ApplyRequest
	5,  // 4: parallax.plugin.v1.Target.Ready:input_type -> parallax.plugin.v1.ReadyRequest
	7,  // 5: parallax.plugin.v1.Target.Reset:input_type -> parallax.plugin.v1.ResetRequest
	9,  // 6: parallax.plugin.v1.Target.Contract:input_type -> parallax.plugin.v1.ContractRequest
	1,  // 7: parallax.plugin.v1.Target.Prepare:output_type -> parallax.plugin.v1.PrepareResponse
	4,  // 8: parallax.plugin.v1.Target.Apply:output_type -> parallax.plugin.v1.ApplyResponse
	6,  // 9: parallax.plugin.v1.Target.Ready:output_type -> parallax.plugin.v1.ReadyResponse
	8,  // 10: parallax.plugin.v1.Target.Reset:output_type -> parallax.plugin.v1.ResetResponse
	10, // 11: parallax.plugin.v1.Target.Contract:output_type -> parallax.plugin.v1.ContractResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_target_proto_init() }
func file_plugin_v1_target_proto_init() {
	if File_plugin_v1_target_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_target_proto_rawDesc), len(file_plugin_v1_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_target_proto_goTypes,
		DependencyIndexes: file_plugin_v1_target_proto_depIdxs,
		MessageInfos:      file_plugin_v1_target_proto_msgTypes,
	}.Build()
	File_plugin_v1_target_proto = out.File
	file_plugin_v1_target_proto_goTypes = nil
	file_plugin_v1_target_proto_depIdxs = nil
}
